### ISSUE TITLE
Add REST API

### ISSUE THREAD

**Issue by noisecapella** [mitodl/lore#100]
Acceptance Criteria:
- [x] Create a Django app called  rest
- [x] Integration with Django rest framework app
- [x] Github style (https://developer.github.com/v3/#pagination) pagination ( http://www.django-rest-framework.org/api-guide/pagination/)
- [x] Authentication ( session based for now ?)

Optionally (looks like @noisecapella has started):
- [x] vocabulary rest API

**Comment by noisecapella** [comment]
Are we using HATEOAS @Ferdi?

**Comment by Ferdi** [comment]
I would keep it very simple for now. E.g. Just enough for us to implement the admin forms.

**Comment by Ferdi** [comment]
@noisecapella Can you split this into 2 PRs as described at #138  ?

**Comment by noisecapella** [comment]
@ferdi Can you be more specific? What needs to be moved out of the PR linked above?

**Comment by Ferdi** [comment]
@noisecapella I missed your description of this issue. Looks like you have defined a clear scope.

**Comment by Ferdi** [comment]
@noisecapella I have changed the description of this issue to add some more details about what to expect. @noisecapella  good ?

**Comment by noisecapella** [comment]
Yes these tasks all look good

**Comment by pdpinch** [comment]
closed via #106
