### ISSUE TITLE
As a user, I want a stable production app

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#101]
One of the takeaways from our demo today is that the physics team needs a production system by the time our next demo ~6/29. 

Please add a checklist to this issue to identify any decisions that need to be made.
- [x] It needs to be fast (responsive to users)
- [ ] What's the name?
- [x] Where will it be deployed?
- [x] How will it be backed up?
- [x] How will we scale?
- [x] How much do we think it will cost?

**Comment by pdpinch** [comment]
@carsongee any follow up comments on this?

**Comment by carsongee** [comment]
I just need the name I think.  I figured, Heroku, heroku, heroku where the answer to the other three and letting travis do the deploy to heroku on a release branch unless that makes us uncomfortable.

**Comment by pdpinch** [comment]
It's Ok as long as it doesn't limit or scalability, or our options to do something else if we stop liking Heroku.

**Comment by carsongee** [comment]
We have docker too, and many things are compatible with heroku, so IBM BlueMix, dotCloud, elastic beanstalk, ec2 container service, etc, etc are all options as well.

**Comment by carsongee** [comment]
My intention here is to just add a couple lines to the travis config to deploy to lore-release on Heroku when the release branch passes tests (similar to what is there for lore-ci).  That application on Heroku will be configured with a connection string to an RDS PostgreSQL DB with hot standby failover and connection via SSL with daily backups (30 day retention), medium size instances, and 100GiB of storage. I will also connect it to bonsai production level ElasticSearch connection: https://addons.heroku.com/bonsai#production, a 100MIB Redis Cloud redis instance: https://addons.heroku.com/rediscloud#100, and https://addons.heroku.com/papertrail#choklad for logging.

Additionally, I plan to wire it up to our production CAS instance for authentication, have it scaled to 2 1x instances for the Web dynos and 1 1x worker.  I plan to use campus e-mail for e-mail configuration, and S3 for django file storage on a dedicated bucket called odl-lore-release.

I also intend on creating a DNS alias for it on our domain.  I just need to know what that is, and I'll generate the certificate with IS&T, do the DNS registration, setup a CNAME to Heroku, and configure the Heroku app to use the certificate and the CNAME.

**Comment by pdpinch** [comment]
Can we estimate the monthly bill on this? At this point, it's OK to omit the usage charges on S3 and RDS. 

@Ferdi what's our name? lore.mitx.mit.edu ??

**Comment by pdpinch** [comment]
@carsongee did you confirm the meaning of "shared memory" in the bonsai configuration (see below)?

![screen shot 2015-06-17 at 2 48 37 pm](https://cloud.githubusercontent.com/assets/430126/8215725/08a4822a-1500-11e5-8408-39a6bb219e77.png)

**Comment by carsongee** [comment]
I did not, but reading between the lines on their FAQ.  I'm sure it is on shared VMs with multiple customers sharing disk/CPU/memory, but not data or elasticsearch processes.  If we just assume that, which is the worst case for data security, is that bad enough we need to confirm/look elsewhere?  I'll go ahead and work up the cost estimate.  That should be pretty quick

**Comment by carsongee** [comment]
## Per Month cost (to start)

Heroku: $75
Bonsai: $50
Redis: $10
RDS: $133.92 for a 31 day month
S3 (worst case): $0.32
Total: $269.24

**Comment by pdpinch** [comment]
@Ferdi is it OK for Carson to proceed with this? If Bonsai ends up being a weak link, we can move elasticsearch to Amazon EC2

**Comment by pdpinch** [comment]
Closed via #205

**Comment by pwilkins** [comment]
LORE production runs on http://lore-release.herokuapp.com and is accessed at http://lore.odl.mit.edu
