### ISSUE TITLE
move all views to the UI app

### ISSUE THREAD

**Issue by ShawnMilo** [mitodl/lore#108]
Requested by @Ferdi.

**Comment by pdpinch** [comment]
Blocked by #107 and PR #115

**Comment by noisecapella** [comment]
Didn't notice this before I merged the PR but the tests for the forms are still in their respective apps.

**Comment by ShawnMilo** [comment]
Yep, that's why I made #114 (which you and I have already commented on). It makes sense to move tests when we're done moving everything else, so we only have to do it once.

**Comment by noisecapella** [comment]
Yes, forgot about that issue
