### ISSUE TITLE
move tests to ui app

### ISSUE THREAD

**Issue by ShawnMilo** [mitodl/lore#114]
After #107 and #108, it doesn't make sense to leave the tests for views and forms in the other apps.

Leave the tests that only test the functions and models that remain in the app, such as model and API tests.

**Comment by noisecapella** [comment]
I agree except for tests on the API functions and the models

**Comment by ShawnMilo** [comment]
Which API(s)? The REST API, the taxonomy API, learningresource API, or the importer API?

With everything else moving, I don't see any reason not to just collapse it down to one app.

**Comment by noisecapella** [comment]
I mean the tests for taxonomy/api.py, etc since they just interact with the models. But I don't have a strong opinion, and it's probably cleaner to keep the tests together than split them up like this

**Comment by ShawnMilo** [comment]
I agree tests should stay with what they're testing. If a test file is clearly testing only models or the API functions, then it makes sense to leave them alone.

**Comment by pdpinch** [comment]
closed by #188
