### ISSUE TITLE
Document REST api

### ISSUE THREAD

**Issue by Ferdi** [mitodl/lore#118]
- Documentation using  https://github.com/apiaryio/api-blueprint
- Integrate with https://apiary.io/ ( we don't have to)

http://docs.lore.apiary.io/

**Comment by pdpinch** [comment]
- [X] Merge this draft to master
- [x] Change the branch that's tied to apiary

**Comment by pdpinch** [comment]
@Ferdi how do we change the branch on the apiary docs?

We could set it to master or, in a few days we should have a release branch.

**Comment by pdpinch** [comment]
Ok. Apiary is working off master now. It should update whenever there is a commit.
