### ISSUE TITLE
Add manage taxonomies slide drawer to repository page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#122]
See http://pureui.com/c/mit/lore/build001/

The Taxonomies tab should use a REST call to get a list of vocabularies and their possible values (when available) (this probably needs it's own story with more detail)

The add vocabulary tab should display the form currently at https://lore-ci.herokuapp.com/repositories/another-repo/vocabularies/vocab1/ (this probably needs another story)

**Comment by carsongee** [comment]
So, I totally did the other panel, and not the manage taxonomies panel...woops

**Comment by carsongee** [comment]
This was half done by #248
