### ISSUE TITLE
Set-up django haystack to see if it meets our needs

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#124]
Once django-haystack and elastic search are set-up, make a determination of whether they can meet our needs:
- [ ] Can build an index based on import
- [ ] full-text search (including stemming)
- [ ] some mechanism to limit text search to text (not XML tags)
- [ ] faceting based on fixed facets
- [ ] can update the index when user adds metadata (terms)
- [ ] faceting based on user-defined facets
- [ ] need a way to omit some items from results (duplicates, items without names, etc.)

The alternative would be to use a native interface to our search engine (probably elastic search or solr)

**Comment by ShawnMilo** [comment]
It looks like Haystack is good, and based on yesterday's conversation, @Ferdi is supporting Haystack + Elasticsearch. Should we close this ticket in favor of #120?

**Comment by Ferdi** [comment]
Closing
