### ISSUE TITLE
Add audit fields to all tables.

### ISSUE THREAD

**Issue by ShawnMilo** [mitodl/lore#134]
As a developer who develops and supports LORE, I'd like automatic timestamps added to each record when it is created and when it is modified. This is simple with Django models by creating a subclass of `models.Model` which has [datetime](https://docs.djangoproject.com/en/1.8/ref/models/fields/#datetimefield) fields using the `auto_now` and `auto_now_add` options, then making all of our models a subclass of the "audit class" instead of `models.Model`.

This has been discussed in #81. Initially we just want the timestamp fields, but may add a UUID field. This UUID field will not be the primary key, but foreign keys _could_ switch to using this UUID field from the primary key, making relationships explicit even when exported outside LORE.

**Comment by ShawnMilo** [comment]
A quick search brought up the [AuthStampedModel](http://django-audit-log.readthedocs.org/en/latest/change_tracking.html) and the [TimeStampedModel](https://github.com/django-extensions/django-extensions/blob/master/django_extensions/db/models.py).

The `AuthStampedModel` doesn't have timestamps and stores the session key unnecessarily. The `TimeStampedModel` is part of [django-extensions](https://github.com/django-extensions/django-extensions), and adding a dependency with more than 8,000 lines of Python for this model doesn't seem like a good idea.

As long as we're keeping our base model simple (a few fields of metadata), I think we're better off making our own.

**Comment by noisecapella** [comment]
Should slugs be added to every model by default? It's looking like anything we interact with in the API will require a slug

**Comment by carsongee** [comment]
This is the one I had looked at, and has those features: https://pypi.python.org/pypi/django-auditable-models/1.0

if we wanted to add extra fields, we could extend it, but considering the simplistic nature of the code in that project, I'd have no problem doing it ourselves

**Comment by ShawnMilo** [comment]
The model looks very close to what we want. However, the only thing really in there is the model with extra fields, pretty much as we'd create it. Everything else in the file is `pass`.

It also relies on [django-cached-user](https://github.com/bitzeppelin/django-cached-user/blob/master/cached_user/middleware.py) by the same author, which uses middleware which uses threadlocals. My knowledge may be out of date, but [last I heard](https://groups.google.com/forum/#!searchin/django-users/threadlocals/django-users/OSz9FvUkIXU/Lbai2VQVDNEJ) (directly from core Django developers), using threadlocals was considered bad.

We haven't discussed saving the user ID automatically, but we're already doing it as part of the import, so it probably isn't a big deal and we just want the date fields for now (and maybe UUIDs later). So, I think we should just make our own. We're almost certain to add to it, so having to have an additional dependency doesn't seem worthwhile.

**Comment by carsongee** [comment]
cool :+1:
