### ISSUE TITLE
Cascade deletes on vocabularies and terms

### ISSUE THREAD

**Issue by noisecapella** [mitodl/lore#136]
This should remove `on_delete=models.PROTECT` from the models so that deletes will cascade. I talked with @cg about delete functionality and this is what he prefers in order to maintain database integrity. I think the alternative is doing the deletes by hand which may be more error prone. Any opinions @ShawnMilo?

**Comment by ShawnMilo** [comment]
Well, preferably nothing ever gets deleted if it's still related to something else. Worst-case scenario, deleting a taxonomy item deletes a LearningResource, and that would be terrible.

If the LearningResources are left alone and deletions in the taxonomy app only cascade within the taxonomy app, then that _seems_ okay to me, although it would be best if it could be confirmed that they weren't currently associated with any `learningresources.models` first. But if this kind of deletion is a standard part of the curator's authority, then of course it's fine. A message like "this term is related to _n_ LearningResources, are you sure you want to delete it?" would be nice.

**Comment by noisecapella** [comment]
I don't think anything else has references to the taxonomy models so I believe deletes on vocabularies or terms should not cascade to other models. We should definitely add some tests for these scenarios no matter what we do though.

**Comment by pwilkins** [comment]
Where are permissions on taxonomies/vocabularies described?

**Comment by pdpinch** [comment]
Permissions on taxonomies are described on page 7 of the [design document](https://docs.google.com/document/d/13gzDte36eRErjW7zQj8VRX2S218FgPZLxjEQLTSS1aA/) and in #26

I'm not sure why that's relevant to the issue here though?
