### ISSUE TITLE
Move /learningresources to /repositories/<repo_slug>/learningresources

### ISSUE THREAD

**Issue by noisecapella** [mitodl/lore#137]
In the process we may want to move the /repositories/<slug> urls to its own file for cleanliness

**Comment by giocalitri** [comment]
this should be higher priority: #151 depends deeply on this

**Comment by giocalitri** [comment]
@Ferdi: inputs?

**Comment by Ferdi** [comment]
I agree

**Comment by giocalitri** [comment]
ok, so I will work on this before #151
