### ISSUE TITLE
Search: Set up indexing to occur during import.

### ISSUE THREAD

**Issue by ShawnMilo** [mitodl/lore#142]
From #120.

Set up indexing to occur during import.

**Comment by Ferdi** [comment]
@ShawnMilo do you have anything in mind how to do that ?  E.g.  https://github.com/django-haystack/celery-haystack ?

**Comment by ShawnMilo** [comment]
Haystack has a feature to do that. Since the import is happening asynchronously anyway, that should be fine.

**Comment by carsongee** [comment]
Won't we also need this when resources get tagged?  Will we have to use signals or is there a more haystack way to do it?

**Comment by ShawnMilo** [comment]
@Ferdi, @carsongee, so far it looks like Haystack's [Signal Processors](http://django-haystack.readthedocs.org/en/latest/signal_processors.html) are the best way to do that. They update the indexes for each record on save.

**Comment by ShawnMilo** [comment]
This ticket is closed by the following line in `lore/settings.py`, as added in #147.

``` python
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'
```

I've opened #155 to address updating the index on taxonomy changes.
