### ISSUE TITLE
As a developer I would like to test my branches easily on heroku without bothering other developers

### ISSUE THREAD

**Issue by carsongee** [mitodl/lore#143]
Look at messing around with the Heroku beta feature, Review Apps, https://devcenter.heroku.com/articles/github-integration-review-apps

**Comment by blarghmatey** [comment]
@bdero this is already enabled isn't it?

**Comment by bdero** [comment]
No - review branches are only enabled on MM, TP, and CCXCon. We should revisit this if/when Lore starts getting stories again, but for now I think we can leave it be. One thing to consider is that lore-ci has a worker dyno and elasticsearch among other things, so cost is a consideration.

**Comment by shaidar** [comment]
If/When we go back to doing development on LORE, we can open a new issue.
