### ISSUE TITLE
As a developer I would like to have third party CSS and JavaScript packages

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#15]
- [x] add a packange manager
- [x] add bootstrap support

**Comment by Ferdi** [comment]
:+1: 

@carsongee 's PR looks good.  bower or browserify ?

**Comment by carsongee** [comment]
Browserify solves a different problem, preprocessing javascript in templates via require statements, bower just downloads modules.  This issue wasn't to create an asset pipeline, which is still something we need to do as well, but is not coupled to bower at all.  I would like to make that piece a separate issue/story.

**Comment by Ferdi** [comment]
sounds good

**Comment by Ferdi** [comment]
see #17

**Comment by carsongee** [comment]
The tasks say add bootstrap, you sure you want me to do that now, or just wait until we need it?

**Comment by Ferdi** [comment]
We can move that to a separate issue, if you prefer.
