### ISSUE TITLE
Update search index when taxonomy items are changed.

### ISSUE THREAD

**Issue by ShawnMilo** [mitodl/lore#155]
Changes made to taxonomy items for a LearningResource should take effect in the search immediately.

**Comment by Ferdi** [comment]
@ShawnMilo now sure what you have in mind here.  When you add/edit a term for a learningresource,  that would trigger a post_save (?) signal on the learningresrouce, so it will get reindexed -- based on what you did in #147.

**Comment by ShawnMilo** [comment]
If a `LearningResource` object has terms added or removed, we will need to add an
[m2m-changed](https://docs.djangoproject.com/en/1.8/ref/signals/#m2m-changed)
signal, because the actual `LearningResource` doesn't get re-saved -- the save
happens in the hidden intermediate table automatically created by the use
of the [ManyToManyField](https://docs.djangoproject.com/en/1.8/ref/models/fields/#django.db.models.ManyToManyField)

Just to make sure, I threw together a little Django project with a `post-save` signal and checked when the model was saved versus the many-to-many field getting a new item. Adding a many-to-many item doesn't trigger the original model's post-save.

**Comment by Ferdi** [comment]
Got it, thanks!
- Sent from my phone

**Comment by ShawnMilo** [comment]
Closing; will be handled as a detail in #159.
