### ISSUE TITLE
Enable ElasticSearch in Heroku

### ISSUE THREAD

**Issue by carsongee** [mitodl/lore#157]
We need to have our settings file handle using an elastic search provider in Heroku.  Either https://elements.heroku.com/addons/searchbox, https://elements.heroku.com/addons/foundelasticsearch, https://devcenter.heroku.com/articles/bonsai, or we could run our own in AWS and point our instances at it if we don't like either of those.

**Comment by pdpinch** [comment]
@carsongee was this closed by #171 ?

**Comment by carsongee** [comment]
It was closed outside a PR since it was just a configuration task (as it turns out)
