### ISSUE TITLE
Search: Facets for dynamic metadata 

### ISSUE THREAD

**Issue by Ferdi** [mitodl/lore#158]
See also #120 
Continue to built on #144 by adding facets for dynamic metadata ((course, run and learningresource type)

![loredynfacets](https://cloud.githubusercontent.com/assets/125561/8149814/cc1d4768-129f-11e5-9708-11cec9311d11.png)

**Comment by ShawnMilo** [comment]
Branch: [feature/skm/158_faceted_search](https://github.com/mitodl/lore/tree/feature/skm/158_faceted_search). I'm working off of [this documentation](http://django-haystack.readthedocs.org/en/latest/faceting.html), but it's not returning facets to the template.

I've worked around that for the display. However, without having `facets` available in the template, there doesn't seem to be a way to filter results.

I think it shouldn't be difficult to intercept the querystring in the view and further filter the `SearchQuerySet`, but then the `FacetedSearchForm` and `FacetedSearchView` are not being used, and we may as well stick with `SearchView` and `SearchForm`.

**Comment by pdpinch** [comment]
Can you throw your branch up on Heroku? 

---

I am mobile.

**Comment by pdpinch** [comment]
@ShawnMilo sorry for sending you down the rabbit hole with heroku. 

This is a really key feature and it's worth spending some time getting it right. If this really is a blocker, we may have to reconsider ElasticSearch and/or Haystack.

**Comment by ShawnMilo** [comment]
@pdpinch I don't believe it's a blocker. I think @carsongee even resolved it already. I just put it aside because, as I understood it, you wanted it on Heroku so others could look at it and help me past the problem I was having, but @giocalitri figured it out so there was no need.

**Comment by Ferdi** [comment]
Just tested the PR a bit and it looks like we are making good progress.

I have a question - It looks like currently you cant filter learning resources that are EITHER 'chapter' OR problem.  I'm not saying that we should or shouldn't be able to, but I wanted to understand what the options are technically. 

Sometime that behaviour is desirable. For example 
- http://www.shoes.com/product-list2 
  You can select `color = "black" OR color="yellow"`
  The same for "brands" facet
- http://www.custommade.com/search/furniture/outdoor/
  You can select `type="chair" or type="table"`

Is something like this easily achievable ?  With haystack ?

**Comment by ShawnMilo** [comment]
It [may not be](https://groups.google.com/d/msg/django-haystack/xWhpYu1stjA/q_iBMQx78dIJ) achievable using Haystack alone, but it's definitely possible [with Elasticsearch](https://gist.github.com/mattweber/1947215). I even found [an example](http://distinctplace.com/2014/07/29/build-zappos-like-products-facets-with-elasticsearch/) that compared the functionality to Zappos.

According to [this](http://django-haystack.readthedocs.org/en/latest/faceting.html) Haystack documentation:

> Facets are chainable, like most SearchQuerySet methods. However, unlike most SearchQuerySet methods, they are NOT affected by filter or similar methods. The only method that has any effect on facets is the narrow method (which is how you provide drill-down).

As I read that, facets can only narrow the search. When it mentions "filter or similar methods," I believe it includes [filter_or](http://django-haystack.readthedocs.org/en/latest/searchqueryset_api.html?highlight=filter_or#SearchQuerySet.filter_or), which is the only "or" functionality I've found in Haystack's documentation.

If we have any Elasticsearch or Haystack experts at MIT I'd like to consult with them. It's something I can figure out, but it would take some studying of Elasticsearch's API and DSL.
