### ISSUE TITLE
Roles and permissions: Create a lore_admin role 

### ISSUE THREAD

**Issue by Ferdi** [mitodl/lore#160]
Users in that group/role will have permission to create repositories.  (see #149 and #26  )   
- [ ] add a fixture that creates the group
- [ ] documentation

**Comment by pdpinch** [comment]
@carsongee @giocalitri I think this is done, as described. 

We don't have a UI for this role, but I think that's OK?

**Comment by pdpinch** [comment]
I'm closing this. There's no documentation, but I don't think it's necessary.
