### ISSUE TITLE
XAnalytics

### ISSUE THREAD

**Issue by Ferdi** [mitodl/lore#166]
Xanalytics app will be a layer between the LORE system and MITx analytics system (xanalytics). It will connect with the xanalytics web service and get and update the relevant metatada in LORE database. 
- [x] Define the protocol of communication between LORE and Xanalytics. Xanalytics team will provide the apis for us to integrate
- [x] Until the API is ready, we will apply some fake data at the time of course import
- [ ] Integrate with xanalytics system using the protocol above.

**Comment by ShawnMilo** [comment]
Will this be read-only from xanalytics?

**Comment by Ferdi** [comment]
Yes, it's read only.  @ShawnMilo and I chatted about this ..

To get started, we can create a json endpoint in lore (for development only). Each response would look like:

```
{
    "org" : "mitx",
    "course_number" : "123",
    "semester" : "fall",
    "url_name" : "636541acbae448d98ab484b028c9a7f6",
    "nr_views" : 120,
    "nr_attempts": 3,
    "average_grade": 0.7,
    "median_grade": 0.6,
    "histogram_of_grades": "ignore for now"
}


```

**Comment by carsongee** [comment]
Is this to mock the analytics service?  If so, it might be easier to use something like https://pypi.python.org/pypi/vcrpy or https://pypi.python.org/pypi/betamax/0.1.6 (though I favor vcrpy), to handcraft an expected response for writing tests, and then when the real server comes online, you can just blow those "cassettes" away and re-record from the real server.

**Comment by ShawnMilo** [comment]
Does xanalytics provide an endpoint for providing course information and receiving this information about `LearningResource`s in bulk, or do we need to perform a query per `LearningResource`?

**Comment by ShawnMilo** [comment]
@carsongee: I was planning on just making a URL in the newly-created `xanalytics` app that returned fake values, then use your `get_var` setup to allow for overrides by environment variable. Then the fake endpoint can be used for unit tests.

**Comment by Ferdi** [comment]
Shawn,  the current thinking is to have a request for each learning
resources. Please feel free to talk to Ike and come up with something that
is easier on both sides. I don't think they have started yet.
- Sent from my phone

**Comment by ShawnMilo** [comment]
Thank you. I will contact Ike.

**Comment by ShawnMilo** [comment]
Pasting here for the record, from Ike:

``` json
{
    "course_id": "XXX",
    "module_medata": [
        {
            "module_id": "YYY",
            "key1": "value1",
            "key2": "value2"
        },
        {
            "module_id": "ZZZ",
            "key1": "value1",
            "key2": "value2"

        }
    ]
}
```

**Comment by pdpinch** [comment]
@Ferdi do we want to close this issue, or should we leave it open until we get the API?
