### ISSUE TITLE
Add a link to request permission to create repositories

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#169]
When a user doesn't have permission to create repositories, replace the button with a link to request it by e-mail (using the django-support-email in settings)

**Comment by pdpinch** [comment]
The setting e-mail should be mitx-support@mit.edu

**Comment by pwilkins** [comment]
@pdpinch Once the link to request permission is clicked and the email is sent, what should happen next?  Flash a message that an email has been sent?  Redirect to another page?

**Comment by pdpinch** [comment]
I thought we were just going to use a mailto: link to open in the user's mail client. 

If it's automatically sending a message, I guess there should be some signal to the user that the message has been sent. Anything that's easy would be fine: could be http://getbootstrap.com/javascript/#alerts

**Comment by pwilkins** [comment]
A mailto: link would be far simpler and provide us with more information.  I'll do that.

**Comment by carsongee** [comment]
:+1: to mailto, but you can just use django messages to do this type of thing.  That is what does the nice little green login confirmation text after login now.  The template just automatically picks those up and shows them

**Comment by pdpinch** [comment]
@carsongee @bdero Jolyon saw the link on lore-ci on Friday, but he noticed that the e-mail address wasn't configured properly -- It's still going to support@example.com

**Comment by pdpinch** [comment]
@pwilkins can you check to see if this is working now?
