### ISSUE TITLE
Add roles to LORE docs

### ISSUE THREAD

**Issue by pwilkins** [mitodl/lore#178]
The Roles package has an API and should be included in the LORE API docs.

**Comment by pdpinch** [comment]
@pwilkins is this addressed by #295 ?

**Comment by pwilkins** [comment]
This is not addressed by #295.  That issue addresses the RESTful API.  This issue is to publish the Roles docstrings into our Sphinx document set.

**Comment by pwilkins** [comment]
Closed by PR #626
