### ISSUE TITLE
Capability to have "unique" versus "free" tagging of taxonomies.

### ISSUE THREAD

**Issue by ShawnMilo** [mitodl/lore#186]
As referred to [here](https://github.com/mitodl/lore/issues/159#issuecomment-112868137)

As a curator, I want the ability to dictate whether a `Vocabulary` I create allows multiple terms for the same `LearningResource`. For example, if I create the vocabulary `Learning Objective`, I would like a `LearningResource` to be tagged with two or more objectives. However, if I create a "Difficultly" vocabulary, I don't want more than a single term (easy, medium, hard) to be able to be associated with any one `LearningResource`.

The `Vocabulary` model should have a field indicating this, and the `taxonomy.api` functions should enforce the rule.

**Comment by pdpinch** [comment]
@pwilkins @ShawnMilo this has been done for some time, hasn't it?

<img width="438" alt="screen shot 2015-10-04 at 10 20 28 pm" src="https://cloud.githubusercontent.com/assets/430126/10271904/2ffc52ee-6ae6-11e5-99b9-a7b854bf1bec.png">
