### ISSUE TITLE
search not returning results from `content_xml` field

### ISSUE THREAD

**Issue by ShawnMilo** [mitodl/lore#197]
When searching on content from the `content_xml` field, results only appear if the same content appears in the content's title. Search should return matches from within the `content_xml` field.

**Comment by pdpinch** [comment]
I haven't been able to confirm this on http://lore-branch-test.herokuapp.com/

Do I need to do something to kick off a rebuild of the index?

**Comment by giocalitri** [comment]
I think the problem in on Travis: if I understood well the message, the build has not been pushed to Heroku even if it was on master:
https://travis-ci.org/mitodl/lore/builds/67654660

**Comment by giocalitri** [comment]
And yes, you have to reindex
`./manage.py rebuild_index`

**Comment by pdpinch** [comment]
Thanks! The rebuild took care of it on http://lore-branch-test.herokuapp.com/

I'm not sure what's up with the CI server.
