### ISSUE TITLE
new repo can access all existing learningresources 

### ISSUE THREAD

**Issue by giocalitri** [mitodl/lore#219]
Steps to recreate:
1- create a repo "foo-repo"
2- import a course inside repo "foo-repo"
3- let's assume the learningresource "foo-learn" is inside "foo-repo"
4- create repo "bar-repo"
5- the learningresource "foo-learn" is inside "bar-repo" (even if it should not)

**Comment by ShawnMilo** [comment]
On what commit?

**Comment by giocalitri** [comment]
on lore-ci

**Comment by pdpinch** [comment]
Was this fixed by #217 ?

@pwilkins can you confirm?

**Comment by pdpinch** [comment]
Actually, #217 was @ShawnMilo 's PR.

**Comment by giocalitri** [comment]
I guess this was not a real bug: we found it during the tests of my PRs before the deployment to production but the reason was that the latest code has not been delivered.
