### ISSUE TITLE
As a user I would like to be redirected to the login page if I haven't logged in

### ISSUE THREAD

**Issue by carsongee** [mitodl/lore#223]
Currently when you go to a protected listing page without logging in, it raises an error but doesn't redirect you to the login page.

**Comment by amir-qayyum-khan** [comment]
@carsongee by protected listing page you mean open a repo? Because I found issue when I open a repo direct without login it throws exception instead of redirect

**Comment by pdpinch** [comment]
That's exactly what we want to change. 

---

I am mobile.

**Comment by amir-qayyum-khan** [comment]
fix @pdpinch 

Thanks
