### ISSUE TITLE
Create "learning object detail" page

### ISSUE THREAD

**Issue by Ferdi** [mitodl/lore#23]
The view in the sliding window although sliding should be ignored and let just be a simple page in this version

![06_loview](https://cloud.githubusercontent.com/assets/125561/7683061/794d55e2-fd4a-11e4-961c-d89479ca541b.png)

**Comment by ShawnMilo** [comment]
Merged into master with #64.

As described above, it's just a "simple page" -- it just exports the XML. A separate issue is open to deal with styling.

**Comment by pdpinch** [comment]
Styling issue is #77
