### ISSUE TITLE
ManageTaxonomyPermission in rest.permissions

### ISSUE THREAD

**Issue by giocalitri** [mitodl/lore#239]
The check currently is:

```
           manage_taxonomies_permission = '{}.{}'.format(
                Repository._meta.app_label,
                RepoPermission.manage_taxonomy[0]
            )
            return request.user.has_perm(manage_taxonomies_permission, repo)
```

instead it should be:

```
from guardian.shortcuts import get_perms 
RepoPermission.manage_taxonomy[0] in get_perms(request.user, repo)
```

the reason is that in the first case it does not check permissions in the right way in case the permissions are applied to the group.

**Comment by noisecapella** [comment]
We do a similar check for add_repo, should I make the change there too?

**Comment by giocalitri** [comment]
add_repo is a different type of permission: it is not assigned to a group/user for a specific object, but is a general permission

**Comment by giocalitri** [comment]
not a real bug, just a style enhancement
