### ISSUE TITLE
Fix alignment of minus button in membership form in Chrome

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#282]
See https://github.com/mitodl/lore/pull/271#issuecomment-117795981

**Comment by carsongee** [comment]
https://s3.amazonaws.com/uploads.hipchat.com/151776/1097195/L02B2dAHZu8RBwJ/upload.png

**Comment by carsongee** [comment]
Doesn't appear to happen in firefox, but does in chrome at least
