### ISSUE TITLE
Allow curators to delete vocabularies

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#287]
As a curator (and as a QA tester) I need to be able to delete vocabularies. A convenient UI would be a button on the Taxonomies tab of the Manage Taxonomies drawer.

How long will it take to remove a vocabulary from the index? Does this need to be a celery task?

**Comment by noisecapella** [comment]
For the moment you can go to the REST console and there should be an option to delete the vocabulary there.

**Comment by Ferdi** [comment]
See #380
