### ISSUE TITLE
left align text in item type facet

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#288]
![screen shot 2015-07-01 at 9 49 29 pm](https://cloud.githubusercontent.com/assets/430126/8468516/57c7e5a4-203b-11e5-9cb2-5228766cb253.png)

`Vertical` should be left-aligned with `Problem` and `Discussion` in the example above. 

Probably the easiest thing to do is make the glyph for vertical the same number of pixels wide as the others.

**Comment by amir-qayyum-khan** [comment]
fixed

cc @pdpinch

**Comment by giocalitri** [comment]
Yes, this has been fixed by #301: closing the issue
