### ISSUE TITLE
edit learning resource description

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#299]
As a user, I need to write free text descriptions for learning resources. I will edit these in the learning resource drawer and view them in the listing page. 

Part of #163 

![editlearningresource](https://cloud.githubusercontent.com/assets/125561/8151465/ec967c08-12db-11e5-81bc-de2481f6da7c.png)

**Comment by pdpinch** [comment]
@noisecapella was this partially closed by #309?

It seems like I can now enter descriptions, but they don't display in the listing page.

**Comment by noisecapella** [comment]
I'm able to enter descriptions then see those descriptions when I search for the item. It won't update the listing automatically, you would need to refresh the page and make sure the course isn't somewhere else in the listing due to the change of description

**Comment by pdpinch** [comment]
closed by #309 

I didn't realize that a refresh was necessary.
