### ISSUE TITLE
Alignment problem in Manage Taxonomies panel

### ISSUE THREAD

**Issue by giocalitri** [mitodl/lore#307]
The tab titles are not aligned.

Seen in Firefox (Mac) but not on Chrome (Mac).
The same problem is in the [UI design](http://pureui.com/c/mit/lore/build001/).

<img width="715" alt="alignment" src="https://cloud.githubusercontent.com/assets/1005204/8548672/2a0ffa4a-2494-11e5-8371-3e16f0972fc2.png">

**Comment by pwilkins** [comment]
Just a note: The alignment is also broken for Chrome in the designer's site.  http://pureui.com/c/mit/lore/build001/  That at least accounts for the source of the problem.
