### ISSUE TITLE
Vocabulary facets appear to use slug instead of name

### ISSUE THREAD

**Issue by carsongee** [mitodl/lore#318]
It would be nice if we had both available in the template, so we can do CSS type stuff for the checkboxes as well as showing the name the user typed in for their vocabulary,

![image](https://cloud.githubusercontent.com/assets/596029/8575059/f7ec3608-2567-11e5-97d2-fe0a69311807.png)

**Comment by pdpinch** [comment]
@ShawnMilo whatever happened to this? I think you closed Amir's PR #374 in favor of some changes you were going to make. Did those get merged?

**Comment by ShawnMilo** [comment]
Yes, #384 fixed this (merged in PR #397).

**Comment by ShawnMilo** [comment]
Oops. I had a typo in PR #397 which closed #316 instead of #318. Will fix.
