### ISSUE TITLE
Extend reactjs test coverage

### ISSUE THREAD

**Issue by pwilkins** [mitodl/lore#322]
Extend reactjs test coverage

**Comment by amir-qayyum-khan** [comment]
Done

**Comment by giocalitri** [comment]
what is this about?

**Comment by noisecapella** [comment]
Adding unit tests to cover most of manage_taxonomies.jsx

**Comment by giocalitri** [comment]
is it finished?

**Comment by noisecapella** [comment]
No, it depends on the linked PR

**Comment by pdpinch** [comment]
@noisecapella #328 is merged now. Can this be closed?

**Comment by noisecapella** [comment]
Completely forgot to answer that :)
