### ISSUE TITLE
Rename "learning object" to "learning resource"

### ISSUE THREAD

**Issue by Ferdi** [mitodl/lore#34]
From the meeting with Dept. of Physics : 

> The name “Learning Object” is potentially highly confusing. We strongly suggest using a different name > for resources, perhaps “Learning Resource”, which is unambiguous.

Renaming the app and the model are 2 things that come in mind.

**Comment by pdpinch** [comment]
closed via #36

**Comment by ShawnMilo** [comment]
This was handled in #36.
