### ISSUE TITLE
Collapse vocabs/terms ui into a double drop-down

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#346]
This UI change is a solution to the problem that there may be many, many vocabularies in a repository. 

First column allows user to choose vocabulary, second column would be used to choose a term/terms.

**Comment by noisecapella** [comment]
Currently when the Save button is clicked the UI will update each term to whatever is selected at the time. This UI change will limit the user to changing only one term selection at a time. That's not a big deal but it makes the UX clunkier IMHO

**Comment by Ferdi** [comment]
@noisecapella are we talking about the same thing ?  Here is what I have in mind : 

![vocab_assign](https://cloud.githubusercontent.com/assets/125561/8702819/18ffbfce-2ae8-11e5-85be-d143244c3b3d.png)

**Comment by noisecapella** [comment]
I think it would be a clunkier UX since you need to set two selection boxes instead of one. The second box would save its state when the value changes but the first box is just showing you which set of terms you're operating on. What does the '+' mean in your diagram?

**Comment by Ferdi** [comment]
Let say you have 100 vocabularies and user wants to assign 2 terms to the given resource
vocab1: someterm
vocab99: someotherterm

Left diagram:
We list all vocabularies in the page when user actually wants to only use 2 of them. She has to scrooool down to find vocab99

Right diagram:
- User selects vocab1 : someterm  
- clicks +
- Selects vocab99: someotherterm

Make sense ?

**Comment by noisecapella** [comment]
Oh I think I understand now, the user would have two lines for the two vocabularies they want to select, the rest would be left out

**Comment by Ferdi** [comment]
Right.

**Comment by pdpinch** [comment]
Also, we want to provide a tag-style ui for vocabs that support multiple values. Perhaps using https://select2.github.io/examples.html -- see "Tagging support"

**Comment by giocalitri** [comment]
other useful link
https://github.com/JedWatson/react-select

**Comment by noisecapella** [comment]
![18ffbfce-2ae8-11e5-85be-d143244c3b3d](https://cloud.githubusercontent.com/assets/863262/9087760/957a9272-3b5a-11e5-9986-c6915d62dd17.png)

After talking with Jamie about it yesterday I was wondering if this made more sense for a UI mock (excuse the badly thrown together image).

**Comment by Ferdi** [comment]
I had in mind something like this

![vocab_assign](https://cloud.githubusercontent.com/assets/125561/9089133/b4e9fda8-3b61-11e5-818c-40b3d97a7077.png)

**Comment by noisecapella** [comment]
What does the vocab select box on the first row mean? Or the term select box on the row with the plus?

**Comment by Ferdi** [comment]
How is this ?

![vocab_assign_2](https://cloud.githubusercontent.com/assets/125561/9089360/ccd715c6-3b62-11e5-8764-707bf4e68f7d.png)

**Comment by noisecapella** [comment]
Wouldn't the first row's vocab select only ever have one item in it? And the term select on the row with the plus would never have any items in it. Is the intention that the last row is used the same as all the rows before it?

**Comment by Ferdi** [comment]
![vocab_assign_3](https://cloud.githubusercontent.com/assets/125561/9089846/481d570c-3b65-11e5-8c8b-0b26cb0ed18a.png)

> Wouldn't the first row's vocab select only ever have one item in it?

No, if you click on it, you can see all vocabs.  You can even change your mind to select a different vocab. When you do that, the corresponding term select, will be refreshed with terms that belong to that vocab.

> And the term select on the row with the plus would never have any items in it. 
> Again, once you select a vocab, the term select gets populated with terms that belong to that vocab

Make sense ?

**Comment by noisecapella** [comment]
What would happen if you changed vocab 67 to vocab 2 which is what the second row is set to? It seems like the user would be able to set terms from the same vocabulary in two different places which may conflict. This isn't a big problem, just wondering if that's the intent.

Also, when the user changes vocabularies in general would the list of currently selected terms be erased for that row?

**Comment by Ferdi** [comment]
> What would happen if you changed vocab 67 to vocab 2 which is what the second row is set to? It 
> seems like the user would be able to set terms from the same vocabulary in two different places 
> which may conflict. This isn't a big problem, just wondering if that's the intent.

Good question, not sure.  2 ways to deal with it
1. When user select a vocab in one of the rows, that vocab should be removed from all other vocab selects
2. If users selected the same vocab in  >1 row
   row1:  vocab2  terms: term1, term2
   row2:  vocab2  terms: term1, term3

..then the list of terms is merged into one  :  term1, term2, term3 , removing duplicates.

> Also, when the user changes vocabularies in general would the list of currently selected terms be
>  erased for that row?

Yes,  and the select is refreshed with new values

**Comment by jamiefolsom** [comment]
Hi both, chiming in here -- couldn't there just be one menu UI -- have a look for example at the todomvc UI -- in our case, there would be two menus where there's just one text field on that example, but otherwise, it could work the same -- list growing below the UI control -- http://todomvc.com/examples/react/#/

**Comment by Ferdi** [comment]
What @jamiefolsom has in mind is awesome - we just chatted.

**Comment by pdpinch** [comment]
Closed via #500
