### ISSUE TITLE
Collections retrieved through API are limited to 20 items

### ISSUE THREAD

**Issue by noisecapella** [mitodl/lore#347]
The API limits all collections to 20 items with a link to the next 20 items, etc. Currently we do not retrieve the next 20 items for any API call in the UI. We can change this on a case by case basis, maybe move all AJAX calls into utility functions or install a model like Backbone to handle this automatically.

**Comment by giocalitri** [comment]
this can create a bad user experience pretty soon, especially considering what @Ferdi said about the amount of terms that they want to assign to a learning resource: I think this should be priority 1 after the basic functionalities are all implemented 
cc @pdpinch

**Comment by Ferdi** [comment]
20 is the default, right ?  Can developer overrides that on each call if they wanted ?

**Comment by noisecapella** [comment]
No, that's turned off by default. We could turn it on but it may be easier just to have a Javascript function which follows the pagination links automatically
