### ISSUE TITLE
Learning Resource static asset dependencies

### ISSUE THREAD

**Issue by Ferdi** [mitodl/lore#35]
Each learning resource can in principle have its own dependencies. For example, videos have transcript files, problems have images, HTML will often have javascript and CSS files, to name but a few. Links to these dependencies should be stored with each learning resource. 

Furthermore, resources like CSS files and javascript libraries should be noted as library objects which are common to multiple learning resources. Upon export, only one copy of each library resource should be exported.

**Comment by pdpinch** [comment]
Blocked by #113

**Comment by pdpinch** [comment]
This story needs more definition. In particular, how can we find internal dependencies of the included files. 

Are video transcripts going to be a special case?

**Comment by pdpinch** [comment]
Replaced by #123
