### ISSUE TITLE
Search: add informational text to make it clear which fields are searched

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#350]
As a user, I would like to know which fields are searched when doing a full text search.

Suggestion to add a Tool Tip (Bootstrap?) to the search input field.

Needs text.

**Comment by giocalitri** [comment]
this was not just a text to say that the search was going to be performed in some specific fields?

**Comment by pdpinch** [comment]
@giocalitri that's it exactly. 

@ShawnMilo can you remind us here which fields are searched in the full text search?

**Comment by amir-qayyum-khan** [comment]
@pdpinch  please explain use case.

**Comment by pdpinch** [comment]
I updated the description. Did that clarify enough?

**Comment by ShawnMilo** [comment]
@pdpinch: The fields indexed for the search text box are:

`title`, `description`, and `content_xml` with the tags stripped out.

**Comment by Ferdi** [comment]
I think #375 is good enough.
