### ISSUE TITLE
Static asset collision/overwriting

### ISSUE THREAD

**Issue by carsongee** [mitodl/lore#356]
If a person uploads the same course to two different repositories, the static assets from the second time importing the same course will overwrite those that are previously uploaded.  A simple addition of repo slugto the basename should resolve this

**Comment by ShawnMilo** [comment]
The fix will also have to update all existing `StaticAsset`s to use the new location information.

**Comment by giocalitri** [comment]
@ShawnMilo I don't think it's necessary: the risk of collisions with the current path is frankly minimal and it's extremely unlikely that the users uploaded the same course with the same run and with static assets named in the same way but that have different content.
I think we should just solve the problem for the future.
