### ISSUE TITLE
Export: builds gzip'ed file containing XML and static assets

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#387]
```
 go for the simplest possible solution: one XML file for each learning resource, using the url_name
```
- [x] export is an asynchronous task
- [x] user needs a way to know the status of their export
- [x] use Amazon temporary S3 URLs to limit access
- [x] need way to manage collisions of learning resources. Can we use database ids? asset ids
- [x] need way to manage collisions of static assets. 
    This is a little harder than XML collisions because the XML has references to the static files. For now, we will got with last asset wins.

**Comment by pdpinch** [comment]
XML should be organized into folders, with a folder for each XBlock type, e.g. problem, video, vertical, sequential, chapters -- in order to match the structure of OLX. Static files should go into a folder names /static

**Comment by noisecapella** [comment]
Can we change this to first asset wins instead of last asset wins? It makes the coding slightly easier. Current plan is to have first asset keep its name and all other assets append a `_1`, `_2` etc before the extension.

Is it ok if resource XML files are formatted `{id}_{name}.xml`, or is `url_name` very much desired? What if the `url_name` doesn't exist?

**Comment by ShawnMilo** [comment]
Considering that the export order is essentially random, I don't see any reason why not.

**Comment by pdpinch** [comment]
- last asset wins is just as good.
- is {name} equivalent to the display_name attribute in the XML or url_name? I would prefer the later, i.e. {id}_{url_name} with a failover to just {id} when there is no url_name. 
  
  Display names make poor file names (spaces, etc.) and they are more likely to collide (not an issue with the {id} but still confusing for humans)

**Comment by pdpinch** [comment]
This looks done to me. We will probably have some refinements to the ui/ux but those can go into new stories.
