### ISSUE TITLE
Display path on search results view

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#388]
As a user, I would like to see the context for the learning resources in my search results. 

Ideally, the items in the path would be links to open the learning resource panel for the corresponding container resource. 

May need to add path field (in model) to elastic search index.

**Comment by giocalitri** [comment]
the column `materialized_path` contains entries like 
`/course/chapter[9]/sequential[8]/vertical[2]/html` that look like the XPATH to access the node in the XML.

@Ferdi said we want the real values for each node, so I think we need:
1- another field in the learningresource model
2- populate that field during the import
3- a migration to populate all the old entries
~~4- add the new field to the index~~
5- display the path on the listing page
