### ISSUE TITLE
Test import with 8.MReV and 8.MechCx

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#39]
There are two additional courses from Dave Pritchard's group that we should include in the initial release. The "AB experiments" in the 8.MReV example may be troublesome.  

> For testing purpose, I would recommend starting with the latest version of 8.MechCx, which is the course that we just finished running. 
> 
> Also, here's a link to the summer 8.MReV course tar ball with all the AB experiments. It contains some more irregularities caused by inconsistent authoring method over the years (as well as using early beta version of BACKSTAGE), and might be a good challenge for LORE's capability.

These are now in the archive repo as well, at 

https://github.mit.edu/edX-Archives/edX-Archive-8.MReVx-2T2014
https://github.mit.edu/edX-Archives/edX-Archive-8.MechCx-1T2015

**Comment by pdpinch** [comment]
@ShawnMilo FYI

After some preliminary examination, it appears that a "AB Experiment" or "Content Cohort" is applied through a combination of a `user_partitions` section in the policy.json and corresponding `group_access` attributes on the xblock tags (leaf only). So it shouldn't affect import at all. 

However, I'm not sure if the 8.MReV course with "irregularities" mentioned above conforms to this.

**Comment by pdpinch** [comment]
@amir-qayyum-khan has started to look into this from the xbundle end of things. 

See https://github.com/mitodl/xbundle/issues/33 and https://github.com/mitodl/xbundle/issues/34

**Comment by amir-qayyum-khan** [comment]
@pdpinch @ShawnMilo @carsongee 

**On uploading both course on Lore i get exception**
https://gist.github.com/amir-qayyum-khan/a3e01160b35392450ff0
![screen shot 2015-06-03 at 6 46 28 pm](https://cloud.githubusercontent.com/assets/10431250/7961453/20dc24e0-0a21-11e5-9291-b52fcd850e4f.png)

**On going back I see course 
![screen shot 2015-06-03 at 6 49 26 pm](https://cloud.githubusercontent.com/assets/10431250/7961486/4b55780c-0a21-11e5-960e-6b4f1a6c61fd.png)

**Comment by ShawnMilo** [comment]
I have not been able to duplicate the error at all. If you delete your database again and undo any changes you did with `makemigrations`, does it still happen?

I don't see the constraint being created in the migration file.

**Comment by ShawnMilo** [comment]
This is caused by #80. Decision needed.

**Comment by amir-qayyum-khan** [comment]
@ShawnMilo 
I am still getting this issue. FYI What I did

1) Rebase Lore
2) Reset project using git reset --hard mit_origin/master
3) Stop docker docker stop lore_db_1
4) Reset database docker rm lore_db_1
5) docker-compose up

Still getting same issue,

**Comment by pdpinch** [comment]
Amir, try the following:

```
git clean -xdf
boot2docker destroy
boot2docker init --memory=4096
boot2docker up
eval $(boot2docker shellinit)
docker-compose up
```

The `boot2docker destroy` may be the key step for the clean up you need.

**Comment by amir-qayyum-khan** [comment]
ok Peter, let me do it

Thanks

**Comment by amir-qayyum-khan** [comment]
@pdpinch @ShawnMilo fixed exception by running these command.

```
git clean -xdf
boot2docker destroy
boot2docker init --memory=4096
boot2docker up
eval $(boot2docker shellinit)
docker stop lore_db_1
docker rm lore_db_1
docker-compose up
```

By the way now it is showing me imported course (edX-Archive-8.MReVx-2T2014) with 163 pages? Is this behaviour OK?

**Comment by ShawnMilo** [comment]
@amir-qayyum-khan, yeah, that result looks good. It was breaking due to the extra `makemigrations` step you ran. You shouldn't have to do that unless you change the content of a `models.py` yourself.

**Comment by amir-qayyum-khan** [comment]
thanks @ShawnMilo ,

**Comment by ShawnMilo** [comment]
Is this issue ready to be closed?

**Comment by pdpinch** [comment]
@ShawnMilo there's still an open issue in xbundle, https://github.com/mitodl/xbundle/issues/34 -- but on a 2nd look I realize it's in the xml -> course conversion, which isn't a blocker (as yet) for LORE. 

We'll take another look at this later when we're working on export.
