### ISSUE TITLE
Use opaque-keys to validate on import

### ISSUE THREAD

**Issue by noisecapella** [mitodl/lore#395]
Since we're going to use opaque-keys to format URLs and it raises validation errors if our course data is incorrect in some way, we should just use it during the import process so that the user is notified at that moment that the data they're importing has a problem.

**Comment by carsongee** [comment]
And once it is python 3 compat, use it for preview URL generation

**Comment by noisecapella** [comment]
They've marked [the issue](https://openedx.atlassian.net/browse/PLAT-752) as won't fix due to Python 3 not being supported, so I don't think this issue will be fulfillable
