### ISSUE TITLE
Make the listing page elasticsearch powered ONLY

### ISSUE THREAD

**Issue by giocalitri** [mitodl/lore#402]
Make sure to avoid hitting the DB.

Bonus points if we enforce this with exceptions if in the templates someone writes `result.object.<model_field>` that will force Django to hit the DB anyway.

References:
https://django-haystack.readthedocs.org/en/v2.4.0/best_practices.html#avoid-hitting-the-database
https://www.dominicrodger.com/order-n-haystack.html

**Comment by carsongee** [comment]
love the bonus points
