### ISSUE TITLE
Export links sometimes don't update export count

### ISSUE THREAD

**Issue by noisecapella** [mitodl/lore#422]

**Comment by pwilkins** [comment]
This hasn't been fixed.  With no export toggles checked, I shouldn't be able to click this `Export` button, 
<img width="164" alt="screen shot 2015-08-11 at 12 36 42 pm" src="https://cloud.githubusercontent.com/assets/145821/9203530/b9324ef6-4025-11e5-8ff0-f3b4bd51633b.png">

and get this empty export pane:
<img width="258" alt="screen shot 2015-08-11 at 12 36 57 pm" src="https://cloud.githubusercontent.com/assets/145821/9203532/be9bc318-4025-11e5-81be-c14f5c5cb2fe.png">
