### ISSUE TITLE
Workers out of memory

### ISSUE THREAD

**Issue by carsongee** [mitodl/lore#435]
We are exceeding the allocation of memory on our worker instances (512MiB).  It currently reported:

```
2015-07-29T20:27:35.642933+00:00 heroku[worker.1]: Process running mem=639M(124.9%)
2015-07-29T20:27:35.642933+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
```

when processing CC.801.  I can double the workers memory at a cost, but it would be nice to know what our current upper limit is (with our course set). With small violations like this, it won't impact successful imports, and would save us some money to not have to double the workers unless this is common usage for multiple courses

**Comment by pdpinch** [comment]
We'll be testing imports of the physics courses listed in [the wiki](https://github.com/mitodl/lore/wiki/LORE-Project-Status#test-courses). That should give us some data about large courses. 

CC.801 is a bit of an edge case, in that it has 250MB of of static content but its XML size is about the same as 8.01r.

**Comment by carsongee** [comment]
The static files shouldn't change the memory footprint much, since the file is chunked into memory on demand: https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto.py#L199

**Comment by pdpinch** [comment]
In that case, 8.MReV and 8.MechCx will be much worse than CC.801. :fearful:

**Comment by carsongee** [comment]
Yeah, I think that makes the case for someone running these through with a profiler attached to celery.  Celery also has some builtin memory profile tools

**Comment by pdpinch** [comment]
@carsongee was this addressed by the caching changes?

**Comment by carsongee** [comment]
Actually https://github.com/mitodl/lore/pull/515
