### ISSUE TITLE
Successful LearningResource "save" may not be obvious to the user.

### ISSUE THREAD

**Issue by ShawnMilo** [mitodl/lore#439]
If the user is editing the description of a LearningResource and scroll down to the bottom to click the "Save" button, they may have no indication it worked and continue clicking. This is because the confirmation is at the top of the screen and may be invisible.

Possibilities:
- Move the confirmation to the bottom, where the user must be to click "Save."
- Scroll to the top upon click so the confirmation will be in view.

**Comment by giocalitri** [comment]
I think we should show a loader every time the user clicks save

**Comment by Ferdi** [comment]
@giocalitri good idea !

**Comment by pdpinch** [comment]
Jolyon asked for this as well. I'm not sure if we're satisfied with the solution in #466

**Comment by pdpinch** [comment]
@amir-qayyum-khan can we put the message in the same div as the loader -- so as to avoid scrolling altogether

**Comment by noisecapella** [comment]
Can we move the status messages above the buttons and also get rid of the scrolling for the taxonomy tab?

Regarding loaders I feel like we should restrict them to places where there's heavy processing going on. If you look at this comment box for example, github will disable the buttons and other editable elements in the component and place the error message right above the text if there is one. It's enough to communicate to the user that there's something happening but also subtle enough not to attract attention that's unwarranted. Any opinions?

**Comment by pdpinch** [comment]
Regarding the position of the status message, see https://github.com/mitodl/lore/pull/466#issuecomment-139354542

**Comment by pdpinch** [comment]
Two things:

[ ] Since we now have a spinner in use elsewhere, we should use the same spinner here. 
[ ] We've decided to move the alert message next to the button so it will always be in view when the user clicks. This means we don't need to scrolll.
