### ISSUE TITLE
Checkbox for "Allow multiple terms" in the taxonomy panel -> add vocabulary needs to be consistent with the rest of the UI

### ISSUE THREAD

**Issue by giocalitri** [mitodl/lore#450]
Currently it's a simple checkbox

**Comment by jamiefolsom** [comment]
This was closed by https://github.com/mitodl/lore/pull/458, correct, @amir-qayyum-khan?

**Comment by amir-qayyum-khan** [comment]
yes @jamiefolsom ,

#457 was created by me mistakenly from my own fork, thats why i closed it.
