### ISSUE TITLE
Rewrite listing page in React

### ISSUE THREAD

**Issue by noisecapella** [mitodl/lore#455]
This would have several benefits:
- No operations would require a page refresh anymore
- Easier to test listing page (currently there are no tests covering this part)
- Cleaner code
- Easier integration with existing React components

Potential complications:
- Integration with haystack text caching

Any thoughts?

**Comment by Ferdi** [comment]
Each learning resource will be a react component ?  What else will change ?

**Comment by noisecapella** [comment]
There would be a component managing everything as well as other smaller components like the panels, learning resources, and so on. For example if a user wanted to search by a learning resource type, they would click the checkbox, that component would tell the main component that it needs to update the resources on the page, the main component would ask the API for a new set of information and it would rerender the resources in place instead of causing a page refresh like we do now.

**Comment by amir-qayyum-khan** [comment]
In upcoming PR i am going to divide Learning resource in to react components like for example
- Editable description component 
- Learning resource 
- Learning resource list

A  will bind (reuse) panels like learning resource panel, export panel with Learning resource listing.
Will handle permissions and other events in react class.

What do you say @pdpinch @Ferdi

**Comment by Ferdi** [comment]
Would it make sense to start with only "Editable description component" ?   And do the rest on separate PRs ?

**Comment by noisecapella** [comment]
Would anyone mind if I did this instead? I've run out of things to do and I have an idea how to implement this
