### ISSUE TITLE
Export button disappears when resources disappear

### ISSUE THREAD

**Issue by noisecapella** [mitodl/lore#462]
The button should be visible if there are resources in the repository, even if there aren't any on the page at the moment.

**Comment by Ferdi** [comment]
@noisecapella not sure I understand this. How do resources disappear ?

**Comment by noisecapella** [comment]
If you search for 'zebra' there are no resources on the page at the moment so the export button disappears too. It should stick around if there are any learning resources in the repository, not just in the current page.

**Comment by Ferdi** [comment]
Got it,  thanks!
- Sent from my phone

**Comment by pwilkins** [comment]
This issue is updated in #487.  That issue changes the spec on export button visibility.
