### ISSUE TITLE
Update templates to match UI designs

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#477]
We've gotten two more iterations of the UI from the designer. The templates need to be updated to reflect his changes. The nature of the changes were discussed on the odl-engineering-platform list. 

To make it easier to see they changes, they've been put into a separate repo with PRs for each update:
build003: https://github.com/mitodl/loretemplates/pull/1
version004: https://github.com/mitodl/loretemplates/pull/2

**Comment by amir-qayyum-khan** [comment]
@pdpinch  I cant access build003 and version004

**Comment by amir-qayyum-khan** [comment]
@pdpinch what is odl-engineering-platform list, can i see the list of changes decided by you guys.

**Comment by pwilkins** [comment]
@pdpinch What constitutes an acceptance test for this since the code changes are explicitly given?  I'd be inclined to accept this on the basis of finding the code changed as specified.

**Comment by pwilkins** [comment]
Although this passes acceptance testing, parts of it are reverted in #490.
