### ISSUE TITLE
Export button visibility

### ISSUE THREAD

**Issue by Ferdi** [mitodl/lore#487]
I'm not sure  #462 is right.  The export button should only be visible if there are resources to be exported.  By default does not show up at all.

**Comment by ShawnMilo** [comment]
To clarify, do you mean the button never appears until after the user has clicked on some resources to populate their "shopping cart"? Regardless of whether any resources are currently shown on-screen. Once there are items in the cart, the button remains until the items are deleted or the cart is emptied. Is that correct?

**Comment by Ferdi** [comment]
Right, that's what I meant. Makes sense ?

**Comment by ShawnMilo** [comment]
Yes, that makes sense. Like a "check out" button not being available until there's something in the cart.

For uniformity of the UI, do we want to hide it or just disable it?

**Comment by amir-qayyum-khan** [comment]
For this task I will create a PR on the top of George work. Because George is working on refactoring listing.
- In react component inside rendering function i will add check if **Learning resource** count is greater than 0  only then I will add button to container.

cc @pdpinch
