### ISSUE TITLE
learningresource panel tabs render differently on FireFox and Chrome

### ISSUE THREAD

**Issue by pwilkins** [mitodl/lore#489]
The learningresource panel tabs render differently on Firefox and Chrome.  

The learningresource panel tabs on Chrome:
<img width="152" alt="screen shot 2015-08-07 at 8 47 26 pm" src="https://cloud.githubusercontent.com/assets/145821/9148323/2b644336-3d46-11e5-86fa-e16dc4b09481.png">

The learningresource panel tabs on Firefox:
![screen shot 2015-08-07 at 8 48 46 pm](https://cloud.githubusercontent.com/assets/145821/9148319/00d132f0-3d46-11e5-8df9-f7c391d6bc89.png)

@pdpinch @Ferdi

**Comment by carsongee** [comment]
This was already reported in https://github.com/mitodl/lore/issues/391
