### ISSUE TITLE
Revert template change for learningresource list

### ISSUE THREAD

**Issue by pwilkins** [mitodl/lore#490]
Revert breadcrumb styling of the template change implemented in issue #477 - "Update template to match UI designs".

This is the preferred style:
![screen shot 2015-08-10 at 11 03 09 am](https://cloud.githubusercontent.com/assets/145821/9175274/c562d1d8-3f52-11e5-9fe3-531df79e8587.png)

This is the newly introduced style that should be reverted:
![screen shot 2015-08-10 at 11 03 33 am](https://cloud.githubusercontent.com/assets/145821/9175283/cc81300e-3f52-11e5-9c39-1ca1ceb5a474.png)

**Comment by jetej** [comment]
PR for this change at https://github.com/mitodl/loretemplates/pull/3

**Comment by tssheth** [comment]
These changes are in PR https://github.com/mitodl/lore/pull/499
