### ISSUE TITLE
Missing migrations

### ISSUE THREAD

**Issue by carsongee** [mitodl/lore#495]
I'm not sure when it snuck in, but on master there are migrations missing:
on build https://travis-ci.org/mitodl/lore/builds/74935056

```
https://travis-ci.org/mitodl/lore/builds/74935056Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

**Comment by ShawnMilo** [comment]
This is due to me changing `related_name`. Interesting that that requires a migration. I suspect that's a relatively recent development in Django.
