### ISSUE TITLE
Edit vocabulary in taxonomy panel 

### ISSUE THREAD

**Issue by amir-qayyum-khan** [mitodl/lore#504]
##### Requirement

Users may want to edit the vocabulary to , for example, change the types of learning resources that vocabulary applies to.
- [ ] Editing a vocabulary should open the Vocabulary tab and populate the form with current values.

Epic https://github.com/mitodl/lore/issues/380
##### Detail

On clicking edit vocabulary button, I will switch tab and open vocabulary in edit mode. Save button will be change into update. And will add cancel button along with update. On pressing cancel or update I will clear form and switch back to listing tab. In case of update I will update vocabulary. (Will see if there is any need to change API)

cc @pdpinch

**Comment by amir-qayyum-khan** [comment]
@pdpinch @carsongee  @ShawnMilo 

These is no code for update in `VocabularyList`. So what approach should I select. I am little confuse here
- Should I extend my `VocabularyList` with `RetrieveUpdateDestroyAPIView, ListCreateAPIView` and change url to support PUT and DELETE operations
- Should I create a new API only for delete and update operation. which off-course will extend `RetrieveUpdateDestroyAPIView`. Will add new URL for update and delete. Because these 2 methods require Primary key in url
- Customize post to support delete and update? I was looking into that and was getting null constraint error in this case.

Which one should I choose.

**Comment by ShawnMilo** [comment]
I don't know either. I am going through the [quickstart](http://www.django-rest-framework.org/tutorial/quickstart/) myself to understand the framework for #469. The docs seem very good so far, so unless someone else can give you the direct answer, they seem like the best resource.

**Comment by pdpinch** [comment]
I added some UX notes on the PR at https://github.com/mitodl/lore/pull/522#issuecomment-139329588
