### ISSUE TITLE
Deleting a term in taxonomy panel

### ISSUE THREAD

**Issue by amir-qayyum-khan** [mitodl/lore#507]
##### Requirements
- [ ] deleting a term should remove it from all learning resources

Epic https://github.com/mitodl/lore/issues/380
##### Details

On clicking delete term, I will show a confirmation dialog. On confirming I will remove that term and re-render list.

cc @pdpinch

**Comment by amir-qayyum-khan** [comment]
@noisecapella are u working on this task?

**Comment by noisecapella** [comment]
No, feel free to work on it

**Comment by amir-qayyum-khan** [comment]
ok, thanks

**Comment by pdpinch** [comment]
See also https://odl.zendesk.com/agent/tickets/2513

**Comment by amir-qayyum-khan** [comment]
@pdpinch i dont have access to zendesk.

**Comment by pdpinch** [comment]
Sorry about that. It was mostly for my reference. Here's the user's feedback:

> The "X" button in the taxonomy view doesn't allow you to delete an individual taxonomy item (not the entire vocabulary, but just a single item inside the vocabulary).

**Comment by pdpinch** [comment]
closed via #648
