### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#509]

**Comment by pwilkins** [comment]
Who has access to the Google Analytics dashboard?

**Comment by pwilkins** [comment]
I looked at the Google Analytics Dashboard and it hasn't shown any activity since 11PM yesterday, more than 15 hours ago.  Either it updates very slowly or something isn't working.  Google Analytics isn't known for speedy updates so I'm going to assume its just that and "accept" it.
