### ISSUE TITLE
"Tag Style (on the fly)" terms don't work in the learning resource panel

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#510]
As a curator, I'd like to be able create new terms while adding metadata to resources. Choosing "Tag Style" should allow me to create free form terms, but it apparently does not.

**Comment by pdpinch** [comment]
Blocked by #500

**Comment by pwilkins** [comment]
This doesn't work the way I expected.  I expected to open a learningresource pane and enter a previously undefined tag for a tag-style vocabulary.  That isn't working on lore-ci.

**Comment by pdpinch** [comment]
Can we get a link to the repo in question & which vocal you're testing with?

Steps to reproduce may also be necessary.

**Comment by giocalitri** [comment]
What part is not working?

**Comment by pwilkins** [comment]
Steps to reproduce:
1. Open Animating Stuffed Animals on lore-ci.  (request access by emailing PeterP, Brandon, Shawn, Giovanni, or Carson)
2. Open learningresource pane for a LR.
3. Select `Tag-Style Vocabulary` in left hand selector.
4. Enter a term in the text box that isn't already defined. This is the expected behavior.
5. The message says, "No results found."  What should happen is that the term is added to the vocab and to the LR.

**Comment by giocalitri** [comment]
In the LR panel, `Tag-Style Vocabulary` comes after [this request](http://lore-ci.herokuapp.com/api/v1/repositories/animating-stuffed-animals/vocabularies/?type_name=vertical) (I actually clicked on the `vertical` "Introduction: Video and Sequences ", but that is irrelevant).

If you go to that URL you can see that the `Tag-Style Vocabulary` is actually a "managed" vocabulary and not a "free" one:

```
        {
            "id": 160,
            "slug": "tag-style-vocabulary",
            "name": "Tag-Style Vocabulary",
            "description": "Tag-Style Vocabulary",
            "vocabulary_type": "m",
            "required": false,
            "weight": 2147483647,
            "learning_resource_types": [
                "course",
                "chapter",
                "sequential",
                "html",
                "vertical",
                "problem",
                "discussion",
                "video",
                "videosequence"
            ],
            "terms": [
                {
                    "id": 415,
                    "slug": "bashful",
                    "label": "Bashful",
                    "weight": 1
                }
            ],
            "multi_terms": true
        }
```

So I guess you need to create a new vocabulary that is actually a "free" one.

**Comment by pwilkins** [comment]
My error.  I thought I had clicked the "Tag Style" box.  I tried the steps again, taking care to click the right box, and it works properly.
