### ISSUE TITLE
Better navigation of paging in search results

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#513]
As a user, when my search results span multiple pages, I can use the footer navigation to move forward or back one page at a time. I would like to have a way to skip ahead to an arbitrary page in the results, and also a way to know how many pages there are in my results.

**Comment by pdpinch** [comment]
This used to be part of the template, but we removed it. I believe the old code was in the [listing template](https://github.com/mitodl/lore/blob/dd0fdff21f4b36b2ac903a8717528cb7fea0ec38/ui/templates/listing.html#L93-L107)

**Comment by amir-qayyum-khan** [comment]
@pdpinch  Is there any mock up for this task? Any design you are interested in. Or i need to give an idea of representation?

**Comment by pdpinch** [comment]
No mock ups. See if you can make it fit in with the existing < and > navigation. Start with the code linked above?

**Comment by amir-qayyum-khan** [comment]
ok, sure. let me try

**Comment by pdpinch** [comment]
closed by #544
