### ISSUE TITLE
Performance: choosing a (large) facet can take tens of seconds

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#514]
This perplexes me, because text search is pretty speedy. But choosing a facet -- especially a large one -- appears to take a long time, with perceptible delays for setting up, waiting for the server to respond, and processing the response.

**Comment by ShawnMilo** [comment]
Please list steps to recreate the problem, and course(s) so it can be replicated locally.

**Comment by pdpinch** [comment]
Steps to reproduce:

Go to http://lore.odl.mit.edu/repositories/classical-mechanics/?sortby=nr_views&selected_facets=course_exact:8.MechCx
Facet on the first course, "8.MechCx"
i.e. http://lore.odl.mit.edu/repositories/classical-mechanics/?sortby=nr_views&selected_facets=course_exact:8.MechCx

I have seen this take dozens of seconds. At the moment, it's taking about 15 seconds.

**Comment by pdpinch** [comment]
This may need some more measurement. It seems better today. It may simply be due to needing to compile static assets -- which we have a PR #520 already submitted to fix. 

We'll wait and see if #520 addresses this.

**Comment by pdpinch** [comment]
In my testing, this is down to 3-4 seconds. Good enough for now.
