### ISSUE TITLE
Research Elasticsearch DSL

### ISSUE THREAD

**Issue by ShawnMilo** [mitodl/lore#516]
The purpose of this issue is to evaluate the Elasticsearch DSL project for use in LORE. This would enable us to eliminate Haystack (which is broken and poorly maintained of late), and have access to all of Elasticsearch's functionality instead of the lowest common feature set exposed by Haystack for all its backends.

@ferdi found [this](http://elasticsearch-dsl.readthedocs.org/en/latest/index.html#), which is an abstraction of the the `elasticsearch` library we're already using.

In short, it wraps `elasticsearch`'s HTTP/JSON API, which is extremely verbose (requiring the creation of a lot of nested dictionaries), with something that looks a lot more like Django's ORM. It still requires a good understanding of how Elasticsearch works. It does not _replace_ Haystack's functionality. Instead, it throws it away in favor of better control and access to Elasticsearch's full feature set.

There was a [talk](https://www.youtube.com/watch?v=hE359wuHyhs) given about it at the latest DjangoCon given by the author of [the project](https://github.com/elastic/elasticsearch-dsl-py).

---

Example from their docs:

This JSON:

``` json
response = client.search(
    index="my-index",
    body={
      "query": {
        "filtered": {
          "query": {
            "bool": {
              "must": [{"match": {"title": "python"}}],
              "must_not": [{"match": {"description": "beta"}}]
            }
          },
          "filter": {"term": {"category": "search"}}
        }
      },
      "aggs" : {
        "per_tag": {
          "terms": {"field": "tags"},
          "aggs": {
            "max_lines": {"max": {"field": "lines"}}
          }
        }
      }
    }
)
```

is replaced by this Python:

``` python
s = Search(using=client, index="my-index") \
    .filter("term", category="search") \
    .query("match", title="python")   \
    .query(~Q("match", description="beta"))

s.aggs.bucket('per_tag', 'terms', field='tags') \
    .metric('max_lines', 'max', field='lines')

response = s.execute()
```

**Comment by ShawnMilo** [comment]
Compared to Haystack letting a bug that actually makes basic functionality of the project _not work_ for nearly five months, the author of Elasticsearch DSL just closed a ticket after 17 days and [apologized](https://github.com/elastic/elasticsearch-dsl-py/pull/217#event-382529749) for the delay.

**Comment by pdpinch** [comment]
Hardest part is learning the elastic search query language, since this is closer to it than how Haystack does it. 

Probably should change everything all at once: querying and indexing

**Comment by ShawnMilo** [comment]
Closing; this has been replaced by #668 and its children.

**Comment by ShawnMilo** [comment]
For educational purposes: How to use the `elasticsearch` and `elasticsearch-dsl` libraries for our needs:

[YouTube](https://youtu.be/uU66q-8Zofg)
