### ISSUE TITLE
Bug: Import does not accept studio exported course tar.gz files

### ISSUE THREAD

**Issue by carsongee** [mitodl/lore#52]
Currently the import upload will only accept tar.gz files that have a single folder in their root, and then import the course in that folder.  This misses on a major OLX convention that if the root folder contains a course.xml file, the tar file should be imported as a single course, and if there are folders in the tar.gz file without a course.xml file, each folder should be imported as a separate course.

**Comment by ShawnMilo** [comment]
Roger, wilco.

**Comment by pdpinch** [comment]
I believe this will be fixed when @ShawnMilo PRs https://github.com/mitodl/lore/tree/feature/skm/listing

**Comment by ShawnMilo** [comment]
Yes, this is included in the forthcoming PR.

**Comment by ShawnMilo** [comment]
In #64.

**Comment by pdpinch** [comment]
closed via #64
