### ISSUE TITLE
Inconsistent behavior while assigning terms to learning resources

### ISSUE THREAD

**Issue by giocalitri** [mitodl/lore#552]
The database gets updated in the right way, but the index in elasticsearch does not update accordingly, so the terms do not show up all the time in the facets.

**Comment by noisecapella** [comment]
I was able to reproduce this on master. Removing a term from a resource caused the index to update correctly but adding a term to a resource didn't update the index. Refreshing the listing page shows that the facets remain at the values they were before, and the listing when filtering on the relevant term is missing the resource that was just assigned to the term.

**Comment by pdpinch** [comment]
I believe this was fixed by #557, but it requires verification.

**Comment by pdpinch** [comment]
@pwilkins when you get a chance, can you confirm that this is working properly?

**Comment by pwilkins** [comment]
If I add a term to a resource and update the page, the new term appears as a facet.
