### ISSUE TITLE
deleting a member hides member list

### ISSUE THREAD

**Issue by pwilkins** [mitodl/lore#567]
The repository has multiple members, but ... 

![screen shot 2015-08-24 at 6 03 32 pm](https://cloud.githubusercontent.com/assets/145821/9453772/995e964c-4a8a-11e5-9f69-799390825af0.png)

after removing a member, the repository appears to have no members:

![screen shot 2015-08-24 at 6 03 58 pm](https://cloud.githubusercontent.com/assets/145821/9453776/a9793672-4a8a-11e5-8320-0e0a167f5071.png)

**Comment by jamiefolsom** [comment]
Hey @pwilkins -- I am not seeing this issue on master (in other words, deleting a user works as expected -- all others are still visible) -- are you still seeing it? Thanks.

**Comment by pdpinch** [comment]
Which server?

**Comment by pwilkins** [comment]
@pdpinch  http://lore-ci.herokuapp.com/repositories/animating-stuffed-animals/

**Comment by pwilkins** [comment]
@jamiefolsom Yes, I still see it.  Maybe it's specific to that repo?

**Comment by pwilkins** [comment]
Nope.  Just tried it on another repo; same problem.

**Comment by jamiefolsom** [comment]
@pwilkins this appears to be due to `GET /members` taking several minutes, and only after `DELETE /api/v1/repositories/:reponame/members/groups/authors/users/:username/`, for some reason. Hoping @bdero can show me how to use statsd to investigate.

**Comment by noisecapella** [comment]
@jamiefolsom See the related PR

**Comment by jamiefolsom** [comment]
@noisecapella I get it now -- the related PR makes the UI and the client side state consistent with user expectations, even if/when the API response is not completed quickly. Seems like that solves the proximate problem, by not giving the impression that the whole list has been deleted. I will see if I can debug the other issue, related to the slow API response.
