### ISSUE TITLE
Find a better way to display the "--not set--" vocabulary in the UI (facets)

### ISSUE THREAD

**Issue by giocalitri** [mitodl/lore#568]
Currently the term "--not set--" looks pretty inconsistent with the rest of the UI, plus the position of the term in the list of terms for a vocabulary is not always the same (I think it should be always the first or last one, since it is a special term).

**Comment by ShawnMilo** [comment]
Is it not always sorting to the bottom of the list? It should be, at least on the search page.

Where are you seeing the random ordering?

**Comment by giocalitri** [comment]
You are right: it's in the list of terms for a vocabulary that it appears in an inconsistent order: updated the description.

**Comment by ShawnMilo** [comment]
For the facets, the listing is now alphabetical, with the `--not set--` value at the bottom. I suggest the same for this fix, for consistency.

Prior to ticket #512 the facet list was in random order.

**Comment by pdpinch** [comment]
As #540 was reverted, this is on hold until we determine if it is still necessary.

**Comment by giocalitri** [comment]
This is relevant only on the UI point of view

**Comment by pdpinch** [comment]
superseded by #676
