### ISSUE TITLE
As a curator, I want to import a course into the current repository

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#57]
In the current implementation of the course import form, a new repository is created with every import. 

Based on the screen design at https://projects.invisionapp.com/share/YK2WMS4WN#/screens/77439557 it appears that the import button is only available after a user has chosen a repository, and new courses are imported into the current repository.

**Comment by ShawnMilo** [comment]
This was actually already being worked on today as part of #24. The existing implementation was a shortcut to get #21 working, but now it's getting fleshed out.

This issue can be closed, or I'll close it when #24 is merged.

**Comment by pdpinch** [comment]
Excellent. I wasn't sure if it was obvious.
