### ISSUE TITLE
Remove and restore `--not set--` term to LearningResource when terms are added or removed.

### ISSUE THREAD

**Issue by ShawnMilo** [mitodl/lore#572]
# Vocabulary term update

Two features are missing from the initial deliverable of the `--not set--` value.
- Add `--not set--` back automatically when all other terms have been deleted.
- Automatically remove `--not set--` from vocabularies which allow multiple terms when another term has been added.
### Vocabulary with "multi" set to `False`

Only one test:
- Restore `--not set--` value when last term is deleted.

When a different term is selected, the `--not set--` value is replaced,
so there's no need to remove it.
### Vocabulary with "multi" set to `True`
- Restore `--not set--` value when last term is deleted.
- Restore `--not set--` value when any other term is added.

**Comment by ShawnMilo** [comment]
# Automatic removal and addition of `not set` term

When all terms are removed from a LearningResource, the `not set` term
should be automatically added.

When a Term is added to a LearningResource and the Vocabulary allows for multiple Terms, the `not set` value must be automatically removed.

## add_term Taxonomy API function

At present, there is no place in the code where a Term is added to a LearningResource and the `multi_terms` is checked to determine whether to remove the existing Term. The only thing that enforces this rule is in the LearningResourceSerializer, but it only checks that there is only a single value, since it's receiving data from an HTTP POST.

Create a function to do this:

``` python
def add_term(resource, term):
    """
    Add a term to a LearningResource.

    Args:
        resource (LearningResource): Resource to have term added.
        term (Term): Term to add to resource.
    """
    # If the Vocabulary's multi_terms is False, delete the previous term.
    # If the Vocabulary's multi_terms is True, delete the `not set` term if present.
```

## remove_term Taxonomy API function

Ensure that when the last Term is removed from a LearningResource, the
`not set` term is re-added.

``` python
def remove_term(resource, term):
    """
    Remove a term from a LearningResource.

    Args:
        resource (LearningResource): Resource to have term removed.
        term (Term): Term to remove from resource.
    """
    # Remove Term.
    # If the LearningResource has no more terms, add the `not set` term.
```

## Use the new API functions

Code which currently adds or removes terms should be updated to use these
new functions.

## Signals?

Another option is to add a signal handler to listen for the `m2m_changed` signal. This handles any case where code is written which inadvertently avoids using the API functions, or in case of manual intervention via the shell.

If this path is chosen, then logic described above in `add_term` and `remove_term` would remain intact, but would be moved to the signal handler.

**Comment by pdpinch** [comment]
As #540 was reverted, this is on hold until we determine if it is still necessary.

**Comment by pdpinch** [comment]
We approached this differently in #591
