### ISSUE TITLE
Can't uncheck learningresource export link

### ISSUE THREAD

**Issue by pwilkins** [mitodl/lore#585]
Clicking the `Export` link that appears to the left of each learningresource should toggle from checked to unchecked.  It doesn't always do that.

Steps to reproduce:
1. Open the Classical Mechanics repository on lore-ci: http://lore-ci.herokuapp.com/repositories/animating-stuffed-animals/
2. Click the `Export` link for the first learningresource. (arrow turns to check)
3. Click the `Export` link for the second learningresource. (arrow turns to check)
4. Click the `Export` link for the first learningresource. (check turns to arrow)
5. Now click the `Export` link for the second learningresource. (check remains unchanged)

@pdpinch @noisecapella

**Comment by pdpinch** [comment]
"Doesn't always" ?

Is there any pattern to when it does and doesn't work? 

My guess is there's some latency, at least in the state update. Is there anything we can inspect to see if that's the case? 

---

I am mobile.

**Comment by noisecapella** [comment]
I talked to @pwilkins a few minutes ago and this seems to be an intermittent issue. The check marks and the count will update only after receiving a success from the server, and sometimes the server takes a long time to respond. It's a very small amount of data, not sure if there's a performance bottleneck or where it is. Unfortunately we don't have metrics to investigate this at the moment,
