### ISSUE TITLE
"Create repository" page

### ISSUE THREAD

**Issue by Ferdi** [mitodl/lore#6]
Create a page / view in the UI app ( #5 ) that allows users to create repositories 

![02_create](https://cloud.githubusercontent.com/assets/125561/7574383/ed6f8274-f7fa-11e4-8e13-22f4349a7e13.png)

Authentication / Authorization is not important - Anyone can create repos at this point.

**Comment by pdpinch** [comment]
@Ferdi "just the form and nothing else"

**Comment by Ferdi** [comment]
Right, we are focusing on functionality now, not the theming.

**Comment by pdpinch** [comment]
This is now part of #44
