### ISSUE TITLE
"save and close" button

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#607]
As a curator, I'd like a way to quickly save my changes in the learning resource panel and close it, to cut down on clicks. 

Should be a different button from "Save"

![screenshot-lore-ci herokuapp com 2015-09-15 08-17-23](https://cloud.githubusercontent.com/assets/430126/9876243/966f191c-5b82-11e5-85c1-fbfce3d89fbb.png)

**Comment by amir-qayyum-khan** [comment]
@pdpinch  By this you mean enable inline editing of description in Learning resource? #454 
Please explain. 
Thanks

**Comment by pdpinch** [comment]
This is about the Learning Resource panel. #454 is about the listing view. I added a screenshot to the description.

**Comment by amir-qayyum-khan** [comment]
got it thanks
