### ISSUE TITLE
Warn user when closing learning resource panel without saving

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#608]
As a curator, sometimes I accidentally close the learning resource panel before I've saved my changes. It would be nice to have a warning so I don't do that.

**Comment by pdpinch** [comment]
check to see if current status has been saved, use existing bootstrap banner

**Comment by amir-qayyum-khan** [comment]
@pdpinch this PR #522 provides base for this task. I will complete it once #522 get merge.

**Comment by pdpinch** [comment]
PR #741
