### ISSUE TITLE
DataTable.js

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#613]
As a user, I'd like a way to view and sort by terms and other fields on assets, without having to open the learning resource panel. 

We've had many requests to use DataTable.js, possibly as an alternate "curator" view of the learning resource listing page.

**Comment by jamiefolsom** [comment]
I heard this request first hand last week! After a little research, it appears there is some concern that datatable.js is too closely bound to the DOM to be a good fit with React. There are some alternatives however. See: [Griddle](http://griddlegriddle.github.io/Griddle/) and [React-Datagrid](http://zippyui.com/react-datagrid/)

**Comment by pdpinch** [comment]
MVP: alternate view of repository with static view of data
