### ISSUE TITLE
start taxonomy URLs with <repo_slug>

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#65]
i.e.  `/<repo_slug>/vocabulary/<vocabulary_slug>`

**Comment by pdpinch** [comment]
From @carsongee via HipChat:

> we could probably do it with middleware, but I think an include is probably the easiest, let me pull an example
> 
> `url(r'^(?P<repo>[\w_-]+)/', include(taxonomy_urls))`

**Comment by pwilkins** [comment]
closed by #86
