### ISSUE TITLE
Free tagging terms are not loaded in the taxonomy panel until page refreshes

### ISSUE THREAD

**Issue by giocalitri** [mitodl/lore#662]
This used not to be a big deal because the search result page was reloading terms at each refresh (or search, or faceting) of the results. 
Now that we don't reload the page that often any more it is more visible.
Terms need to be reloaded each time we open the taxonomy panel.

**Comment by noisecapella** [comment]
#642 should have fixed this

**Comment by noisecapella** [comment]
Actually I misread this

**Comment by noisecapella** [comment]
This functionality is included in #522
