### ISSUE TITLE
On long vocabulary lists, error messages at top are not visible.

### ISSUE THREAD

**Issue by jamiefolsom** [mitodl/lore#719]
In this case, if you look at the bottom of the long list of vocabularies, you can see that I tried to add the same term twice. What you can't see is that there is an error message (above the viewport) which says I can't do that. It should be adjacent to the entry field.

![screenshot 2015-09-24 13 40 10](https://cloud.githubusercontent.com/assets/882377/10081242/f880ae2c-62c1-11e5-8759-97540861768a.png)

**Comment by pdpinch** [comment]
Would the work in https://github.com/mitodl/lore/pull/466 address this?

**Comment by jamiefolsom** [comment]
Dupe of #466. Closing.
