### ISSUE TITLE
Terms in index not updated when vocabulary is edited

### ISSUE THREAD

**Issue by noisecapella** [mitodl/lore#723]
Introduced by #522, might get fixed by #718. If not we probably need to figure out a signal which handles this case to update the index

**Comment by ShawnMilo** [comment]
@pdpinch This seems like a smallish issue. Any objections to me self-assigning it? @noisecapella  brought it up in the context of #718, and it seems like it's worth taking care of in the near future.

**Comment by noisecapella** [comment]
I have no objections. I'm sure it's just a matter of figuring out which signal to handle, or maybe doing the reindex in the REST framework
