### ISSUE TITLE
LearningObjects listing page 2

### ISSUE THREAD

**Issue by Ferdi** [mitodl/lore#73]
Continue the work done on #24 
- [x] Move "import" link to the top of the page  (see [2])
- [x] Apply new template to the listing (as much as we can ) [3]
- [x] Apply new template to the left navigation ( just the look and feel more than the functionality)  [4]

![mitlore](https://cloud.githubusercontent.com/assets/125561/7951858/d692e1a4-097a-11e5-9e2c-b614020a5f23.png)

Items moved to #75
- change the url of the listing page from /lore/listing/3/1  to /repositories/repo_slug or /repositories/repo_id  (see [1] below)
- Change "import" url from importer/upload/repo_id to   repositories/repo_slug/import or repositories/repo_id/import

**Comment by pwilkins** [comment]
@Ferdi  "Move import link to top of page" as it is in http://pureui.com/c/mit/lore/build001/ where it's named "Import Course"?

**Comment by Ferdi** [comment]
@pwilkins yes, thanks !

**Comment by pdpinch** [comment]
@Ferdi Peter has a PR #87 that replaces the table of resources with divs using Nicholae's styles. Here's a screenshot of a decent-looking page:

![screen shot 2015-06-03 at 9 01 32 pm](https://cloud.githubusercontent.com/assets/430126/7974786/0cb1add8-0a34-11e5-8dec-b79e85808870.png)

We've got a number of issues:
- [ ] Many resources don't have names. The screenshot lists ones that do. 
- [ ] I don't know what's intended for the "Lorem" text. 
- [ ] We're just repeating the "type" icon right now. Those were hardcoded images in Nicholae's template. Peter and I have been talking about how to do it CSS. 
- [ ] Course number and run aren't currently in the view. Presumably they can be added. 
- [ ] The view data is faked (I assume that's not a problem for now though)

Is this worth deploying before the demo tomorrow?

**Comment by Ferdi** [comment]
looking ..

**Comment by Ferdi** [comment]
I made some small changes in this commit http://bit.ly/1Ij6J0f that addresses your questions above.  
![screenshot 2015-06-03 22 09 46](https://cloud.githubusercontent.com/assets/125561/7975562/6d2031cc-0a3d-11e5-9486-5e5f146969a1.png)
