### ISSUE TITLE
As a user, I'd like URLs that contain my repo name

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#75]
Gathering related items from #73 and #74 
- [x] change the url of the listing page from /lore/listing/3/1 to /repositories/repo_slug
- [x] change /lore/create_repo to repositories/new
- [x] Change "import" url from importer/upload/repo_id to repositories/repo_slug/import or repositories/repo_id/import
- [x] change /lore/welcome  to  /home

**Comment by noisecapella** [comment]
What about the export url? Currently it's export/<resource_id>

**Comment by noisecapella** [comment]
And status?

**Comment by ShawnMilo** [comment]
I believe status is deprecated. It was just there so I could demo that the original import branch did something.

**Comment by noisecapella** [comment]
Ok, I'm moving status to /status and export to /export and we can remove those in a later story

**Comment by noisecapella** [comment]
Remove status I mean, move export somewhere appropriate

**Comment by Ferdi** [comment]
Yes, good point on "export".  

export/resource_id should be changed to   learningresources/resource_id  or     /lr/resource_id

**Comment by pdpinch** [comment]
fixed via d826cfb
