### ISSUE TITLE
Vocabularies for all repositories are showing on list page for each repo.

### ISSUE THREAD

**Issue by ShawnMilo** [mitodl/lore#758]
When a repository is viewed, along the left there are filters for vocabularies that exist in other repositories, even if they don't exist for the current repository.

**Comment by ShawnMilo** [comment]
The front-end problem has been addressed in the short term by #759.

The description of this issue assumes cross-repository queries will not happen (they currently do not), but @Ferdi has some information which changes that. Please see him before working on this, unless he's added the new requirements as comments below.

**Comment by ShawnMilo** [comment]
Updated this ticket to be only about the bug, not the mappings, since #759 refers to closing this one. #760 was created to track the separate mapping concern.

**Comment by pdpinch** [comment]
@ShawnMilo @noisecapella can we close this now?

**Comment by ShawnMilo** [comment]
Yes, #759 fixed this.
