### ISSUE TITLE
500 error on a brand new LORE, after creating a new repo

### ISSUE THREAD

**Issue by giocalitri** [mitodl/lore#769]
Create a brand new LORE env, create the repo, after the redirect to the repo page, there is this error:

<img width="1434" alt="screen shot 2015-10-16 at 3 49 32 pm" src="https://cloud.githubusercontent.com/assets/1005204/10551853/89fb65d8-741d-11e5-8e2b-ab168f3f0bab.png">

The stack trace is:

```
web_1     | [2015-10-16 19:36:56] ERROR 26 [django.request] base.py:256 - [7981ee47f83d] - Internal Server Error: /api/v1/repositories/repo1/search/
web_1     | Traceback (most recent call last):
web_1     |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
web_1     |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1     |   File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
web_1     |     return view_func(*args, **kwargs)
web_1     |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 87, in view
web_1     |     return self.dispatch(request, *args, **kwargs)
web_1     |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 466, in dispatch
web_1     |     response = self.handle_exception(exc)
web_1     |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 463, in dispatch
web_1     |     response = handler(request, *args, **kwargs)
web_1     |   File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 30, in _wrapped
web_1     |     return_value = f(*args, **kwargs)
web_1     |   File "/src/rest/views.py", line 945, in list
web_1     |     queryset = self.filter_queryset(self.get_queryset())
web_1     |   File "/src/rest/views.py", line 937, in get_queryset
web_1     |     return construct_queryset(repo_slug, query, selected_facets, sortby)
web_1     |   File "/src/search/api.py", line 71, in construct_queryset
web_1     |     terms=terms,
web_1     |   File "/src/search/utils.py", line 184, in search_index
web_1     |     return SearchResults(search)
web_1     |   File "/src/search/utils.py", line 357, in __init__
web_1     |     get_conn()  # We don't need the return value; just for it to exist.
web_1     |   File "/src/search/utils.py", line 75, in get_conn
web_1     |     index_name=INDEX_NAME
web_1     | ReindexException: Unable to find index haystack
web_1     | [16/Oct/2015 19:36:56] "GET /static/ui/images/logo-mit-lore@2x.png HTTP/1.1" 304 0
```

**Comment by ShawnMilo** [comment]
This is _technically_ not a bug. It was an [intentional change](https://github.com/mitodl/lore/commit/40c4e4f94a486a8ecda4a340891958cbeab7174e#diff-bc726219d9791dc6279a70929de3be49R55). The argument was that if something was wrong with the Elasticsearch index it should fail loudly instead of automatically trying to fix it.

**Comment by giocalitri** [comment]
I know, but I guess that trying to create the index when we create the first repo is not a big deal: it will never happen in production anyway (or did I misunderstand the scope of this?)

**Comment by noisecapella** [comment]
Yes, what @ShawnMilo said. It should work after reindex

**Comment by giocalitri** [comment]
@noisecapella I know, I was among the people who wanted that specific exception.
What I'm saying is that having an empty DB and getting that error is weird. But if we do not have an easy solution, we can close this issue.

**Comment by noisecapella** [comment]
I think the alternative would be to do it in a migration, but we had a migration timeout issue (cc @bdero), and it doesn't really fit with the idea of migrations being for database changes. If there were some code Django runs on first load we may want to put a reindex there but otherwise I think the cleanest way is to require it be done manually

**Comment by giocalitri** [comment]
ok.
So this is not a bug: closing the issue
