### ISSUE TITLE
User can create empty slug using a character like '('

### ISSUE THREAD

**Issue by noisecapella** [mitodl/lore#773]
If something which uses slugs, like a repository, vocabulary, or term, uses invalid characters for a name or label, the newly generated slug will be an empty string. This can cause many problems and we should change our slug generation methods to add some prefix to the slug to guard against this case.

I think this is a severe bug but not enough to delay the next release

**Comment by giocalitri** [comment]
My opinion is that we should add validation to the forms: in case like that, we should be able to return an error to the form and visualize it.

Currently `slugify` is used in the following code:

```
exporter/api.py
14:from django.utils.text import slugify
55:        return slugify(url_name)[:200]

exporter/tests/test_export.py
13:from django.utils.text import slugify
45:                url_name=slugify(resource.url_name)[:200],

learningresources/migrations/0015_backfill_curator_vocabularies.py
5:from django.utils.text import slugify
29:            slug=slugify("{0}_{1}_backfill".format(VOCAB_NAME, repo.id)),
48:            slug=slugify("{0}_{1}_backfill".format(label, vocab_id)),

learningresources/migrations/0016_revert_backfill.py
8:from django.utils.text import slugify

learningresources/models.py
14:from django.utils.text import slugify
174:            slug = slugify(self.name)
177:                slug = "{0}{1}".format(slugify(self.name), count)

rest/tests/test_export.py
11:from django.utils.text import slugify
77:                    url_name=slugify(resource.url_name)[:200],

roles/tests/test_api.py
8:from django.utils.text import slugify
34:        self.repo_slug = slugify(self.repo_name)
37:        self.repo_slug2 = slugify(self.repo_name2)

roles/tests/test_utils.py
9:from django.utils.text import slugify
27:        self.repo_slug = slugify(self.repo_name)

taxonomy/migrations/0003_populate_slug_values.py
5:from django.utils.text import slugify
17:        slug = slugify(term.label)  # pragma: no cover
21:            slug = "{0}{1}".format(slugify(term.label), count)  # pragma: no cover

taxonomy/models.py
6:from django.utils.text import slugify
55:            slug = slugify(self.name)
58:                slug = "{0}{1}".format(slugify(self.name), count)
86:            slug = slugify(self.label)
89:                slug = "{0}{1}".format(slugify(self.label), count)
```

And it seems to me that the sensitive places are 
1- the `repository` model
2- the `vocabulary` model
3- the `term` model

For the Repository the solution seems to be to add a validator to the `ui.forms.RepositoryForm`

For the other two we can add a validation step in the view before calling the method of the overridden class to create the object.

**Comment by noisecapella** [comment]
It may be easiest to alter the save functions to fill in a slug name if slugify returns an empty string, something like 'empty', 'empty1', 'empty2', etc. As a part of this we should write migrations to change slugs if the slug is an empty string in the database.

**Comment by giocalitri** [comment]
That was my very first idea: I feel like it is not the right approach, but I'm open to a discussion.

The problem I see with this approach is "how to keep the counter": do you have an easy solution?

**Comment by giocalitri** [comment]
I guess we could use the same word and let `slugify` do that work for us, actually

**Comment by noisecapella** [comment]
```
        if self.id is not None:
            is_update = True
            old_slug = get_object_or_404(Repository, id=self.id).slug
        slug = slugify(self.name)
        count = 1
        while Repository.objects.filter(slug=slug).exists():
            slug = "{0}{1}".format(slugify(self.name), count)
            count += 1
        self.slug = slug
```

After `slug = slugify(...)` we can say, if slug == '', slug = 'empty'. The rest of the code can remain to prevent against duplicates

**Comment by giocalitri** [comment]
where is this code?

**Comment by noisecapella** [comment]
`Repository.save()`

**Comment by giocalitri** [comment]
I guess the right approach is to create a custom `slugify` function that takes care of replace the base string with a constant string in case `slugify(original_string) == ''`
