### ISSUE TITLE
fix uniqueness constraints

### ISSUE THREAD

**Issue by ShawnMilo** [mitodl/lore#80]
It appears that #39 is being caused by constraints in the models that aren't in the migrations, probably caused by typos reported by @noisecapella, where `Meta` was spelled `meta`, and therefore didn't result in the migration file containing the appropriate constraints.

Deleting and recreating the migration file results in this diff:

``` diff
@@ -76,4 +74,12 @@ class Migration(migrations.Migration):
             name='repository',
             field=models.ForeignKey(to='learningresources.Repository'),
         ),
+        migrations.AlterUniqueTogether(
+            name='learningresource',
+            unique_together=set([('course', 'uuid')]),
+        ),
+        migrations.AlterUniqueTogether(
+            name='course',
+            unique_together=set([('repository', 'org', 'course_number', 'run')]),
+        ),
     ]
```

---

This requires a decision. Right now, the courses do not have UUIDs in the LearningResources, which means we have to create them. However, creating a _universally unique_ value is already going to guarantee uniqueness, so the database constraint seems unnecessary. 

So do we remove the `unique_together` or do we leave it and generate UUIDs?

If we decide to leave the constraint in, we will have to regenerate the initial migration again, so dev and Heroku databases will need to be deleted again to prevent errors.

**Comment by Ferdi** [comment]
It would be great to add UUIDs as we have discussed earlier.  For now, whatever it's easier for you.

**Comment by ShawnMilo** [comment]
Right now it's just easier to remove the `Meta` section altogether, since it's actually not functioning.

**Comment by ShawnMilo** [comment]
Although easier isn't necessarily better, come to think of it. Because it will allow data to be imported that will violate the constraints we want to add later.

So remove constraints now and accept that all databases will have to be deleted some time between now and actual release, or redo the migrations and delete all databases today. I think that would be better in the long run.

I change my vote to "fix it now."

**Comment by ShawnMilo** [comment]
Closing in favor of #134.
