### ISSUE TITLE
Bad preview links in production

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#814]
Reported by Chen in https://odl.zendesk.com/agent/tickets/2557

> The "Missing Title" issue might be more complicated than that. Try searching for "angular momentum homework" in 8.MReVx, and looked for problems. On the first page you'll see something like this:
> 
> If you click preview on the "Missing Title" ones, they'll actually bring you to a blank course page. The vertical "checkpoint 2: Momentum of a System" only contains two problems, both have names and are found. The two "Missing Title" ones are actually ghost components that don't exist (or at least invisible to me).

In my investigation, it appears that some of the (problem) learning resources have bad preview links that are missing the `/jump_to_id/` followed by `url_name`. 

For example, from this search:

http://lore.odl.mit.edu/repositories/classical-mechanics/?selected_facets=course_exact%3A8.MReVx&selected_facets=resource_type_exact%3Aproblem

these resources have bad preview URLs:

http://lore.odl.mit.edu/api/v1/repositories/classical-mechanics/learning_resources/21192/
http://lore.odl.mit.edu/api/v1/repositories/classical-mechanics/learning_resources/21271/

I can't imagine why, but it seems that every resource with a missing title has a bad preview URL.

**Comment by pwilkins** [comment]
I'm finding this difficult to test because I don't have a good way to identify the same learning resource in different repositories.  I can reproduce the problem in production, and so far I haven't been able to reproduce it on lore-ci.  @pdpinch @noisecapella

**Comment by noisecapella** [comment]
It's difficult to test because there are 3 PRs which may overlap in solving the problem. Currently on lore-ci you should be able to import Classical Mechanics and the preview link should be fixed. However when PR #835 is merged you won't even see these extra resources anymore after importing.

**Comment by pdpinch** [comment]
Can you load 8.MReV in lore-rc?

**Comment by pwilkins** [comment]
I will do that now.

**Comment by pwilkins** [comment]
@pdpinch 8.MReV is loaded in lore-rc in the 'release-testing' repository.

**Comment by pdpinch** [comment]
Here is a resource in 8.MReV that should not have been created:

https://lore-rc.herokuapp.com/repositories/release-testing/?selected_facets=course_exact%3A8.MReVx https://lore-rc.herokuapp.com/repositories/release-testing/?selected_facets=course_exact:8.MReVx

It has a bad Preview link. 

Here is a resource from CC.801 that is legit:

https://lore-rc.herokuapp.com/repositories/release-testing/?selected_facets=course_exact%3ACC.801 https://lore-rc.herokuapp.com/repositories/release-testing/?selected_facets=course_exact:CC.801

It also has a bad Preview link.

Both of these resources' preview links should be fixed by George's changes. The first one will also not be created in future imports.

**Comment by pwilkins** [comment]
@pdpinch The URLs you provide above don't identify LRs, they identify courses.  So this doesn't clarify the problem.  Do we even have a way to provide a link to a specific LR?

**Comment by pdpinch** [comment]
Oops! I'm not sure how I convinced myself that works. 

Here's the 8.MRevX LR that should not have been created:

https://lore-rc.herokuapp.com/api/v1/repositories/release-testing/learning_resources/31140/?remove_content_xml=true https://lore-rc.herokuapp.com/api/v1/repositories/release-testing/learning_resources/31140/?remove_content_xml=true

It's a <problem> that was a child of another <problem>

Here's a CC.801 LR that has a bad preview link. It's a legit LR, but the preview is broken on release. 

http://lore.odl.mit.edu/api/v1/repositories/classical-mechanics/learning_resources/27750/?remove_content_xml=true http://lore.odl.mit.edu/api/v1/repositories/classical-mechanics/learning_resources/27750/?remove_content_xml=true

It's working now on lore-rc, as far as I can can tell.
