### ISSUE TITLE
Need indication whether course import worked

### ISSUE THREAD

**Issue by pwilkins** [mitodl/lore#861]
"After importing a course, (LORE) takes you back to the home screen without mention if the import worked or did not work.  It appears like the import does not work because your new course does not appear on the list."

_Mary Ellen proposes this remedy,_ "On the import page, describe what to expect to happen after clicking to import or have a message appear that says the import is successful, refresh your page to see the course."

> _Source: Mary Ellen Wiltrout's Notes_ 
> https://docs.google.com/document/d/10iJdumDyhArCXjZVMVAtcYmpCzzqZYcsI7B9LxDg0m8/edit?pref=2&pli=1

@pdpinch

**Comment by pdpinch** [comment]
Is this addressed adequately by https://github.com/mitodl/lore/pull/810 ?

**Comment by pwilkins** [comment]
It is a duplicate of issue #111 and addressed adequately in PR #810.
