### ISSUE TITLE
As a user, I need to sort resources in the listing view

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lore#89]
Sort orders include alphabetical, run, course. We should be able to sort acending or descending. 

@ShawnMilo can we default to sorting in the order that blocks appear in the courseware?

**Comment by ShawnMilo** [comment]
Would sorting it by the `materialized_path` work? (That's one of the fields visible on the listing page.) Is that what you mean? All courses first, then all chapters, then all verticals, etc.?

**Comment by pdpinch** [comment]
Not exactly what I was looking for, but it might be a better default than the current alphabetical. 

Can you submit a small PR, or point out the code to change to try it?

**Comment by ShawnMilo** [comment]
It's `get_resources` in `learningobjects/api.py`.The whole function is currently just one line that returns a queryset.

If you want it ordered by any other field (currently `title`), then that's easy. If you want it sorted by something other than a straightforward `WHERE` clause, then it will be more complicated.

**Comment by ShawnMilo** [comment]
@pdpinch Ideally, how would you like sorting to work? I'll use that as a starting point.

Also, is it maybe unnecessary in the short term, if the search engine will provide more robust sorting options?

**Comment by pdpinch** [comment]
I agree that the search engine should provide sorting and in the demo today, we decide to move search up the schedule (and move a few other things out).

I'll close this for now.
