### ISSUE TITLE
Fix styling of "Listing" link in Welcome page menu bar

### ISSUE THREAD

**Issue by pwilkins** [mitodl/lore#96]
This was introduced with the Welcome page cleanup - PR#93.  The "Listing" text is the wrong font.  It may not need a fix since the design may change anyway but I've added it here just to track it.

![screen shot 2015-06-04 at 11 45 57 am](https://cloud.githubusercontent.com/assets/145821/7988720/e7ff8b52-0ab2-11e5-9519-3cdc36d0b92f.png)

**Comment by Ferdi** [comment]
I thought I removed it  ?

**Comment by pdpinch** [comment]
I'm pretty sure it's gone. I think Peter was looking at an outdated branch.

**Comment by pdpinch** [comment]
To put a finer point on it, I don't see this anymore on https://lore-ci.herokuapp.com
